/*
 RequireJS Copyright (c) 2004-2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT, GPL or new BSD license.
 see: http://github.com/jrburke/requirejs for details
 RequireJS i18n Copyright (c) 2004-2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT, GPL or new BSD license.
 see: http://github.com/jrburke/requirejs for details
 RequireJS text Copyright (c) 2004-2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT, GPL or new BSD license.
 see: http://github.com/jrburke/requirejs for details
 RequireJS jsonp Copyright (c) 2004-2010, The Dojo Foundation All Rights Reserved.
 Available via the MIT, GPL or new BSD license.
 see: http://github.com/jrburke/requirejs for details

 jQuery JavaScript Library v1.4.2
 http://jquery.com/

 Copyright 2010, John Resig
 Dual licensed under the MIT or GPL Version 2 licenses.
 http://jquery.org/license

 Includes Sizzle.js
 http://sizzlejs.com/
 Copyright 2010, The Dojo Foundation
 Released under the MIT, BSD, and GPL Licenses.

 Date: Sat Feb 13 22:33:48 2010 -0500
*/
var require;
(function(){function A(n){return L.call(n)==="[object Function]"}function z(n,b,x){var v=o.plugins.defined[n];if(v)v[x.name].apply(null,x.args);else{v=o.plugins.waiting[n]||(o.plugins.waiting[n]=[]);v.push(x);b.defined.require(["require/"+n])}}function W(n,b){var x=o.plugins.callbacks[n]=[];o.plugins[n]=function(){for(var v=0,m;m=x[v];v++)if(m.apply(null,arguments)===true&&b)return true;return false}}var F={},o,u,H=[],y,B,U,N,O,M,R=/^(complete|loaded)$/;y=!!(typeof window!=="undefined"&&navigator&&
document);var L=Object.prototype.toString;if(typeof require!=="undefined")if(A(require))return;else M=require;require=function(n,b){if(typeof n==="string"&&!A(b))return require.get(n,b);return require.def.apply(require,arguments)};require.def=function(n,b,x,v){var m=null,D,V,P,T;if(typeof n==="string"){D=n.indexOf("!");if(D!==-1){P=n.substring(0,D);n=n.substring(D+1,n.length)}if(!require.isArray(b)){v=x;x=b;b=[]}v=v||o.ctxName;if((D=o.contexts[v])&&(D.defined[n]||D.waiting[n]))return require}else if(require.isArray(n)){v=
x;x=b;b=n;n=null}else if(require.isFunction(n)){x=n;v=b;n=null;b=[]}else{m=n;n=null;if(require.isFunction(b)){v=x;x=b;b=[]}v=v||m.context}v=v||o.ctxName;D=o.contexts[v];if(!D){D={contextName:v,config:{waitSeconds:7,baseUrl:o.baseUrl||"./",paths:{}},waiting:[],specified:{require:true,exports:true,module:true},loaded:{require:true},defined:{},modifiers:{}};D.defined.require=require;o.plugins.newContext&&o.plugins.newContext(D);D=o.contexts[v]=D}if(m){if(m.baseUrl)if(m.baseUrl.charAt(m.baseUrl.length-
1)!=="/")m.baseUrl+="/";T=D.config.paths;require.mixin(D.config,m,true);if(m.paths){for(V in m.paths)V in F||(T[V]=m.paths[V]);D.config.paths=T}if(m.priority){require(m.priority);D.config.priorityWait=m.priority}if(m.deps||m.callback)require(m.deps||[],m.callback);if(!b)return require}if(b){m=b;b=[];for(V=0;V<m.length;V++)b[V]=require.splitPrefix(m[V],n)}m=D.waiting.push({name:n,deps:b,callback:x});if(n){D.waiting[n]=m-1;D.specified[n]=true}if(n&&x&&!require.isFunction(x))D.defined[n]=x;P&&z(P,D,
{name:"require",args:[n,b,x,D]});if(o.paused||D.config.priorityWait)(o.paused||(o.paused=[])).push([P,n,b,D]);else{require.checkDeps(P,n,b,D);require.checkLoaded(v)}return require};require.mixin=function(n,b,x){for(var v in b)if(!(v in F)&&(!(v in n)||x))n[v]=b[v];return require};require.version="0.11.0";o=require.s={ctxName:"_",contexts:{},plugins:{defined:{},callbacks:{},waiting:{}},isBrowser:y,isPageLoaded:!y,readyCalls:[],doc:y?document:null};require.isBrowser=o.isBrowser;o.head=y?document.getElementsByTagName("head")[0]:
null;require.plugin=function(n){var b,x,v,m=n.prefix,D=o.plugins.callbacks,V=o.plugins.waiting[m],P;b=o.plugins.defined;v=o.contexts;if(b[m])return require;b[m]=n;P=["newContext","isWaiting","orderDeps"];for(b=0;x=P[b];b++){o.plugins[x]||W(x,x==="isWaiting");D[x].push(n[x])}if(n.newContext)for(x in v)if(!(x in F)){b=v[x];n.newContext(b)}if(V){for(b=0;v=V[b];b++)n[v.name]&&n[v.name].apply(null,v.args);delete o.plugins.waiting[m]}return require};require.pause=function(){if(!o.paused)o.paused=[]};require.resume=
function(){var n,b,x;if(!o.contexts[o.ctxName].config.priorityWait){if(o.paused){x=o.paused;delete o.paused;for(n=0;b=x[n];n++)require.checkDeps.apply(require,b)}require.checkLoaded(o.ctxName)}};require.checkDeps=function(n,b,x,v){if(n)z(n,v,{name:"checkDeps",args:[b,x,v]});else for(n=0;b=x[n];n++)if(!v.specified[b.fullName]){v.specified[b.fullName]=true;b.prefix?z(b.prefix,v,{name:"load",args:[b.name,v.contextName]}):require.load(b.name,v.contextName)}};require.isArray=function(n){return L.call(n)===
"[object Array]"};require.isFunction=A;require.get=function(n,b){if(n==="exports"||n==="module")throw new Error("require of "+n+" is not allowed.");b=b||o.ctxName;var x=o.contexts[b].defined[n];if(x===undefined)throw new Error("require: module name '"+n+"' has not been loaded yet for context: "+b);return x};require.load=function(n,b){var x=o.contexts[b],v;o.isDone=false;x.loaded[n]=false;v=require.nameToUrl(n,null,b);require.attach(v,b,n);x.startTime=(new Date).getTime()};require.jsExtRegExp=/\.js$/;
require.normalizeName=function(n,b){if(n.charAt(0)==="."){b=b.split("/");b=b.slice(0,b.length-1);n=b.concat(n.split("/"));for(u=0;b=n[u];u++)if(b==="."){n.splice(u,1);u-=1}else if(b===".."){n.splice(u-1,2);u-=2}n=n.join("/")}return n};require.splitPrefix=function(n,b){var x=n.indexOf("!"),v=null;if(x!==-1){v=n.substring(0,x);n=n.substring(x+1,n.length)}if(b)n=require.normalizeName(n,b);return{prefix:v,name:n,fullName:v?v+"!"+n:n}};require.nameToUrl=function(n,b,x){var v,m,D;x=o.contexts[x].config;
if(n.indexOf(":")!==-1||n.charAt(0)==="/"||require.jsExtRegExp.test(n))return n;else if(n.charAt(0)===".")throw new Error("require.nameToUrl does not handle relative module names (ones that start with '.' or '..')");else{v=x.paths;n=n.split("/");for(m=n.length;m>0;m--){D=n.slice(0,m).join("/");if(v[D]){n.splice(0,m,v[D]);break}}b=n.join("/")+(b||".js");return(b.charAt(0)==="/"||b.match(/^\w+:/)?"":x.baseUrl)+b}};require.checkLoaded=function(n){var b=o.contexts[n||o.ctxName],x=b.config.waitSeconds*
1E3,v=x&&b.startTime+x<(new Date).getTime(),m=b.loaded;x=b.waiting;var D="",V=false,P=false,T,ba,fa,X=o.plugins.isWaiting,ja=o.plugins.orderDeps,Y,ka={};if(!b.isCheckLoaded){if(b.config.priorityWait){ba=true;for(Y=0;fa=b.config.priorityWait[Y];Y++)if(!b.loaded[fa]){ba=false;break}if(ba){delete b.config.priorityWait;require.resume()}else return}b.isCheckLoaded=true;for(T in m)if(!(T in F)){V=true;if(!m[T])if(v)D+=T+" ";else{P=true;break}}if(!V&&!x.length&&(!X||!X(b)))b.isCheckLoaded=false;else{if(v&&
D){T=new Error("require.js load timeout for modules: "+D);T.requireType="timeout";T.requireModules=D}if(P){b.isCheckLoaded=false;require.isBrowser&&setTimeout(function(){require.checkLoaded(n)},50)}else{b.waiting=[];b.loaded={};ja&&ja(b);for(Y=0;D=x[Y];Y++)require.exec(D,ka,x,b);b.isCheckLoaded=false;if(b.waiting.length||X&&X(b))require.checkLoaded(n);else if(!H.length){o.ctxName="_";o.isDone=true;require.callReady&&require.callReady()}}}}};require.exec=function(n,b,x,v){if(n){var m=n.name,D=n.callback;
D=n.deps;var V,P,T=v.defined,ba,fa=[],X=false;if(m){if(b[m]||m in T)return T[m];b[m]=true}if(D)for(V=0;P=D[V];V++){P=P.name;if(P==="exports"){P=T[m]={};X=true}else P=P==="module"?{id:m,uri:m?require.nameToUrl(m,null,v.contextName):undefined}:P in T?T[P]:b[P]?undefined:require.exec(x[x[P]],b,x,v);fa.push(P)}if((D=n.callback)&&require.isFunction(D)){ba=require.execCb(m,D,fa);if(m)if(X)ba=T[m];else if(m in T)throw new Error(m+" has already been defined");else T[m]=ba}return ba}};require.execCb=function(n,
b,x){return b.apply(null,x)};require.onScriptLoad=function(n){var b=n.target||n.srcElement,x;if(n.type==="load"||R.test(b.readyState)){n=b.getAttribute("data-requirecontext");x=b.getAttribute("data-requiremodule");o.contexts[n].loaded[x]=true;require.checkLoaded(n);b.removeEventListener?b.removeEventListener("load",require.onScriptLoad,false):b.detachEvent("onreadystatechange",require.onScriptLoad)}};require.attach=function(n,b,x){if(require.isBrowser){var v=document.createElement("script");v.type=
"text/javascript";v.charset="utf-8";v.setAttribute("async","async");v.setAttribute("data-requirecontext",b);v.setAttribute("data-requiremodule",x);v.addEventListener?v.addEventListener("load",require.onScriptLoad,false):v.attachEvent("onreadystatechange",require.onScriptLoad);v.src=n;return o.head.appendChild(v)}return null};o.baseUrl=M&&M.baseUrl;if(require.isBrowser&&(!o.baseUrl||!o.head)){y=document.getElementsByTagName("script");U=M&&M.baseUrlMatch?M.baseUrlMatch:/(requireplugins-|require-)?jquery[\-\d\.]*(min)?\.js(\W|$)/i;
for(u=y.length-1;u>-1&&(B=y[u]);u--){if(!o.head)o.head=B.parentNode;if(N=B.src)if(O=N.match(U)){o.baseUrl=N.substring(0,O.index);break}}}if(M){B=require;B(M)}})();
(function(){function A(o,u){u=u.nlsWaiting;return u[o]||(u[o]=u[u.push({_name:o})-1])}function z(o,u,H,y){var B,U,N,O,M,R,L="root";U=H.split("-");N=[];O=A(o,y);for(B=U.length;B>-1;B--){M=B?U.slice(0,B).join("-"):"root";if(R=u[M]){if(H===y.config.locale&&!O._match)O._match=M;if(L==="root")L=M;O[M]=M;if(R===true){R=o.split("/");R.splice(-1,0,M);R=R.join("/");!y.specified[R]&&!(R in y.loaded)&&!y.defined[R]&&N.push(R)}}}if(L!==H)if(y.defined[L])y.defined[H]=y.defined[L];else O[H]=L;N.length&&y.defined.require(N)}
var W=/(^.*(^|\/)nls(\/|$))([^\/]*)\/?([^\/]*)/,F={};require.plugin({prefix:"i18n",require:function(o,u,H,y){var B,U=y.defined[o];B=W.exec(o);if(B[5]){o=B[1]+B[5];u=A(o,y);u[B[4]]=B[4];u=y.nls[o];if(!u){y.defined.require([o]);u=y.nls[o]={}}u[B[4]]=H}else{if(u=y.nls[o])require.mixin(u,U);else u=y.nls[o]=U;y.nlsRootLoaded[o]=true;if(B=y.nlsToLoad[o]){delete y.nlsToLoad[o];for(H=0;H<B.length;H++)z(o,u,B[H],y)}z(o,u,y.config.locale,y)}},newContext:function(o){require.mixin(o,{nlsWaiting:[],nls:{},nlsRootLoaded:{},
nlsToLoad:{}});if(!o.config.locale)o.config.locale=typeof navigator==="undefined"?"root":(navigator.language||navigator.userLanguage||"root").toLowerCase()},load:function(o,u){var H=require.s.contexts[u],y=W.exec(o),B=y[4];if(y[5]){o=y[1]+y[5];u=H.nls[o];if(H.nlsRootLoaded[o]&&u)z(o,u,B,H);else{(H.nlsToLoad[o]||(H.nlsToLoad[o]=[])).push(B);H.defined.require([o])}}else H.nlsRootLoaded[o]||require.load(o,u)},checkDeps:function(){},isWaiting:function(o){return!!o.nlsWaiting.length},orderDeps:function(o){var u,
H,y,B,U,N,O,M,R,L,n,b,x=o.nlsWaiting,v;o.nlsWaiting=[];o.nlsToLoad={};for(u=0;B=x[u];u++){y=B._name;U=o.nls[y];n=null;N=y.split("/");R=N.slice(0,N.length-1).join("/");O=N[N.length-1];for(L in B)if(L!=="_name"&&!(L in F))if(L==="_match")n=B[L];else if(B[L]!==L)(v||(v={}))[L]=B[L];else{M={};N=L.split("-");for(H=N.length;H>0;H--){b=N.slice(0,H).join("-");b!=="root"&&U[b]&&require.mixin(M,U[b])}U.root&&require.mixin(M,U.root);o.defined[R+"/"+L+"/"+O]=M}o.defined[y]=o.defined[R+"/"+n+"/"+O];if(v)for(L in v)L in
F||(o.defined[R+"/"+L+"/"+O]=o.defined[R+"/"+v[L]+"/"+O])}}})})();
(function(){var A=["Msxml2.XMLHTTP","Microsoft.XMLHTTP","Msxml2.XMLHTTP.4.0"],z=/^\s*<\?xml(\s)+version=[\'\"](\d)*.(\d)*[\'\"](\s)*\?>/im,W=/<body[^>]*>\s*([\s\S]+)\s*<\/body>/im;if(!require.textStrip)require.textStrip=function(F){if(F){F=F.replace(z,"");var o=F.match(W);if(o)F=o[1]}else F="";return F};if(!require.getXhr)require.getXhr=function(){var F,o,u;if(typeof XMLHttpRequest!=="undefined")return new XMLHttpRequest;else for(o=0;o<3;o++){u=A[o];try{F=new ActiveXObject(u)}catch(H){}if(F){A=[u];
break}}if(!F)throw new Error("require.getXhr(): XMLHttpRequest not available");return F};if(!require.fetchText)require.fetchText=function(F,o){var u=require.getXhr();u.open("GET",F,true);u.onreadystatechange=function(){u.readyState===4&&o(u.responseText)};u.send(null)};require.plugin({prefix:"text",require:function(){},newContext:function(F){require.mixin(F,{text:{},textWaiting:[]})},load:function(F,o){var u=false,H=null,y,B=F.indexOf("."),U=F.substring(0,B),N=F.substring(B+1,F.length),O=require.s.contexts[o],
M=O.textWaiting;B=N.indexOf("!");if(B!==-1){u=N.substring(B+1,N.length);N=N.substring(0,B);B=u.indexOf("!");if(B!==-1&&u.substring(0,B)==="strip"){H=u.substring(B+1,u.length);u="strip"}else if(u!=="strip"){H=u;u=null}}y=U+"!"+N;B=u?y+"!"+u:y;if(H!==null&&!O.text[y])O.defined[F]=O.text[y]=H;else if(!O.text[y]&&!O.textWaiting[y]&&!O.textWaiting[B]){M[B]||(M[B]=M[M.push({name:F,key:y,fullKey:B,strip:!!u})-1]);u=require.nameToUrl(U,"."+N,o);O.loaded[F]=false;require.fetchText(u,function(R){O.text[y]=
R;O.loaded[F]=true;require.checkLoaded(o)})}},checkDeps:function(){},isWaiting:function(F){return!!F.textWaiting.length},orderDeps:function(F){var o,u,H,y=F.textWaiting;F.textWaiting=[];for(o=0;u=y[o];o++){H=F.text[u.key];F.defined[u.name]=u.strip?require.textStrip(H):H}}})})();
(function(){require._jsonp={};require.plugin({prefix:"jsonp",require:function(){},newContext:function(A){require.mixin(A,{jsonpWaiting:[]})},load:function(A,z){var W=A.indexOf("?"),F=A.substring(0,W);W=A.substring(W+1,A.length);var o=require.s.contexts[z],u={name:A},H=require.s.head,y=H.ownerDocument.createElement("script");require._jsonp.f0=function(B){u.value=B;o.loaded[A]=true;require.checkLoaded(z);setTimeout(function(){H.removeChild(y);delete require._jsonp.f0},15)};o.jsonpWaiting.push(u);F=
require.nameToUrl(F,"?",z);F+=(F.indexOf("?")===-1?"?":"")+W.replace("?","require._jsonp.f0");o.loaded[A]=false;y.type="text/javascript";y.charset="utf-8";y.src=F;y.setAttribute("async","async");H.appendChild(y)},checkDeps:function(){},isWaiting:function(A){return!!A.jsonpWaiting.length},orderDeps:function(A){var z,W,F=A.jsonpWaiting;A.jsonpWaiting=[];for(z=0;W=F[z];z++)A.defined[W.name]=W.value}})})();
(function(A,z){function W(){if(!b.isReady){try{m.documentElement.doScroll("left")}catch(a){setTimeout(W,1);return}b.ready()}}function F(a,c){c.src?b.ajax({url:c.src,async:false,dataType:"script"}):b.globalEval(c.text||c.textContent||c.innerHTML||"");c.parentNode&&c.parentNode.removeChild(c)}function o(a,c,d,f,e,i){var j=a.length;if(typeof c==="object"){for(var r in c)o(a,r,c[r],f,e,d);return a}if(d!==z){f=!i&&f&&b.isFunction(d);for(r=0;r<j;r++)e(a[r],c,f?d.call(a[r],r,e(a[r],c)):d,i);return a}return j?
e(a[0],c):z}function u(){return(new Date).getTime()}function H(){return false}function y(){return true}function B(a,c,d){d[0].type=a;return b.event.handle.apply(c,d)}function U(a){var c,d=[],f=[],e=arguments,i,j,r,k,q,w;j=b.data(this,"events");if(!(a.liveFired===this||!j||!j.live||a.button&&a.type==="click")){a.liveFired=this;var E=j.live.slice(0);for(k=0;k<E.length;k++){j=E[k];j.origType.replace(la,"")===a.type?f.push(j.selector):E.splice(k--,1)}i=b(a.target).closest(f,a.currentTarget);q=0;for(w=
i.length;q<w;q++)for(k=0;k<E.length;k++){j=E[k];if(i[q].selector===j.selector){r=i[q].elem;f=null;if(j.preType==="mouseenter"||j.preType==="mouseleave")f=b(a.relatedTarget).closest(j.selector)[0];if(!f||f!==r)d.push({elem:r,handleObj:j})}}q=0;for(w=d.length;q<w;q++){i=d[q];a.currentTarget=i.elem;a.data=i.handleObj.data;a.handleObj=i.handleObj;if(i.handleObj.origHandler.apply(i.elem,e)===false){c=false;break}}return c}}function N(a,c){return"live."+(a&&a!=="*"?a+".":"")+c.replace(/\./g,"`").replace(/ /g,
"&")}function O(a){return!a||!a.parentNode||a.parentNode.nodeType===11}function M(a,c){var d=0;c.each(function(){if(this.nodeName===(a[d]&&a[d].nodeName)){var f=b.data(a[d++]),e=b.data(this,f);if(f=f&&f.events){delete e.handle;e.events={};for(var i in f)for(var j in f[i])b.event.add(this,i,f[i][j],f[i][j].data)}}})}function R(a,c,d){var f,e,i;c=c&&c[0]?c[0].ownerDocument||c[0]:m;if(a.length===1&&typeof a[0]==="string"&&a[0].length<512&&c===m&&!Ea.test(a[0])&&(b.support.checkClone||!Fa.test(a[0]))){e=
true;if(i=b.fragments[a[0]])if(i!==1)f=i}if(!f){f=c.createDocumentFragment();b.clean(a,c,f,d)}if(e)b.fragments[a[0]]=i?f:1;return{fragment:f,cacheable:e}}function L(a,c){var d={};b.each(Ga.concat.apply([],Ga.slice(0,c)),function(){d[this]=a});return d}function n(a){return"scrollTo"in a&&a.document?a:a.nodeType===9?a.defaultView||a.parentWindow:false}var b=function(a,c){return new b.fn.init(a,c)},x=A.jQuery,v=A.$,m=A.document,D,V=/^[^<]*(<[\w\W]+>)[^>]*$|^#([\w-]+)$/,P=/^.[^:#\[\.,]*$/,T=/\S/,ba=/^(\s|\u00A0)+|(\s|\u00A0)+$/g,
fa=/^<(\w+)\s*\/?>(?:<\/\1>)?$/,X=navigator.userAgent,ja=false,Y=[],ka=!!(typeof require!=="undefined"&&require.def),ga,ra=Object.prototype.toString,sa=Object.prototype.hasOwnProperty,ta=Array.prototype.push,ma=Array.prototype.slice,Ha=Array.prototype.indexOf;b.fn=b.prototype={init:function(a,c){var d,f;if(!a)return this;if(a.nodeType){this.context=this[0]=a;this.length=1;return this}if(a==="body"&&!c){this.context=m;this[0]=m.body;this.selector="body";this.length=1;return this}if(typeof a==="string")if((d=
V.exec(a))&&(d[1]||!c))if(d[1]){f=c?c.ownerDocument||c:m;if(a=fa.exec(a))if(b.isPlainObject(c)){a=[m.createElement(a[1])];b.fn.attr.call(a,c,true)}else a=[f.createElement(a[1])];else{a=R([d[1]],[f]);a=(a.cacheable?a.fragment.cloneNode(true):a.fragment).childNodes}return b.merge(this,a)}else{if(c=m.getElementById(d[2])){if(c.id!==d[2])return D.find(a);this.length=1;this[0]=c}this.context=m;this.selector=a;return this}else if(!c&&/^\w+$/.test(a)){this.selector=a;this.context=m;a=m.getElementsByTagName(a);
return b.merge(this,a)}else return!c||c.jquery?(c||D).find(a):b(c).find(a);else if(b.isFunction(a))return D.ready(a);if(a.selector!==z){this.selector=a.selector;this.context=a.context}return b.makeArray(a,this)},selector:"",jquery:"1.4.2",length:0,size:function(){return this.length},toArray:function(){return ma.call(this,0)},get:function(a){return a==null?this.toArray():a<0?this.slice(a)[0]:this[a]},pushStack:function(a,c,d){var f=b();b.isArray(a)?ta.apply(f,a):b.merge(f,a);f.prevObject=this;f.context=
this.context;if(c==="find")f.selector=this.selector+(this.selector?" ":"")+d;else if(c)f.selector=this.selector+"."+c+"("+d+")";return f},each:function(a,c){return b.each(this,a,c)},ready:function(a){b.bindReady();if(b.isReady&&(!ka||require.s.isDone))a.call(m,b);else{Y||(Y=[]);Y.push(a)}return this},eq:function(a){return a===-1?this.slice(a):this.slice(a,+a+1)},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},slice:function(){return this.pushStack(ma.apply(this,arguments),
"slice",ma.call(arguments).join(","))},map:function(a){return this.pushStack(b.map(this,function(c,d){return a.call(c,d,c)}))},end:function(){return this.prevObject||b(null)},push:ta,sort:[].sort,splice:[].splice};b.fn.init.prototype=b.fn;b.extend=b.fn.extend=function(){var a=arguments[0]||{},c=1,d=arguments.length,f=false,e,i,j,r;if(typeof a==="boolean"){f=a;a=arguments[1]||{};c=2}if(typeof a!=="object"&&!b.isFunction(a))a={};if(d===c){a=this;--c}for(;c<d;c++)if((e=arguments[c])!=null)for(i in e){j=
a[i];r=e[i];if(a!==r)if(f&&r&&(b.isPlainObject(r)||b.isArray(r))){j=j&&(b.isPlainObject(j)||b.isArray(j))?j:b.isArray(r)?[]:{};a[i]=b.extend(f,j,r)}else if(r!==z)a[i]=r}return a};b.extend({noConflict:function(a){A.$=v;if(a)A.jQuery=x;return b},isReady:false,ready:function(){if(!b.isReady){if(!m.body)return setTimeout(b.ready,13);b.isReady=true;b.callReady()}},callReady:function(){if(b.isReady&&(!ka||require.s.isDone)){if(Y){for(var a,c=0;a=Y[c++];)a.call(m,b);Y=null}b.fn.triggerHandler&&b(m).triggerHandler("ready")}},
bindReady:function(){if(!ja){ja=true;if(m.readyState==="complete")return b.ready();if(m.addEventListener){m.addEventListener("DOMContentLoaded",ga,false);A.addEventListener("load",b.ready,false)}else if(m.attachEvent){m.attachEvent("onreadystatechange",ga);A.attachEvent("onload",b.ready);var a=false;try{a=A.frameElement==null}catch(c){}m.documentElement.doScroll&&a&&W()}}},isFunction:function(a){return ra.call(a)==="[object Function]"},isArray:function(a){return ra.call(a)==="[object Array]"},isPlainObject:function(a){if(!a||
ra.call(a)!=="[object Object]"||a.nodeType||a.setInterval)return false;if(a.constructor&&!sa.call(a,"constructor")&&!sa.call(a.constructor.prototype,"isPrototypeOf"))return false;var c;for(c in a);return c===z||sa.call(a,c)},isEmptyObject:function(a){for(var c in a)return false;return true},error:function(a){throw a;},parseJSON:function(a){if(typeof a!=="string"||!a)return null;a=b.trim(a);if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return A.JSON&&A.JSON.parse?A.JSON.parse(a):(new Function("return "+a))();else b.error("Invalid JSON: "+a)},noop:function(){},globalEval:function(a){if(a&&T.test(a)){var c=m.getElementsByTagName("head")[0]||m.documentElement,d=m.createElement("script");d.type="text/javascript";if(b.support.scriptEval)d.appendChild(m.createTextNode(a));else d.text=a;c.insertBefore(d,c.firstChild);c.removeChild(d)}},nodeName:function(a,c){return a.nodeName&&a.nodeName.toUpperCase()===
c.toUpperCase()},each:function(a,c,d){var f,e=0,i=a.length,j=i===z||b.isFunction(a);if(d)if(j)for(f in a){if(c.apply(a[f],d)===false)break}else for(;e<i;){if(c.apply(a[e++],d)===false)break}else if(j)for(f in a){if(c.call(a[f],f,a[f])===false)break}else for(d=a[0];e<i&&c.call(d,e,d)!==false;d=a[++e]);return a},trim:function(a){return(a||"").replace(ba,"")},makeArray:function(a,c){c=c||[];if(a!=null)a.length==null||typeof a==="string"||b.isFunction(a)||typeof a!=="function"&&a.setInterval?ta.call(c,
a):b.merge(c,a);return c},inArray:function(a,c){if(c.indexOf)return c.indexOf(a);for(var d=0,f=c.length;d<f;d++)if(c[d]===a)return d;return-1},merge:function(a,c){var d=a.length,f=0;if(typeof c.length==="number")for(var e=c.length;f<e;f++)a[d++]=c[f];else for(;c[f]!==z;)a[d++]=c[f++];a.length=d;return a},grep:function(a,c,d){for(var f=[],e=0,i=a.length;e<i;e++)!d!==!c(a[e],e)&&f.push(a[e]);return f},map:function(a,c,d){for(var f=[],e,i=0,j=a.length;i<j;i++){e=c(a[i],i,d);if(e!=null)f[f.length]=e}return f.concat.apply([],
f)},guid:1,proxy:function(a,c,d){if(arguments.length===2)if(typeof c==="string"){d=a;a=d[c];c=z}else if(c&&!b.isFunction(c)){d=c;c=z}if(!c&&a)c=function(){return a.apply(d||this,arguments)};if(a)c.guid=a.guid=a.guid||c.guid||b.guid++;return c},uaMatch:function(a){a=a.toLowerCase();a=/(webkit)[ \/]([\w.]+)/.exec(a)||/(opera)(?:.*version)?[ \/]([\w.]+)/.exec(a)||/(msie) ([\w.]+)/.exec(a)||!/compatible/.test(a)&&/(mozilla)(?:.*? rv:([\w.]+))?/.exec(a)||[];return{browser:a[1]||"",version:a[2]||"0"}},
browser:{}});X=b.uaMatch(X);if(X.browser){b.browser[X.browser]=true;b.browser.version=X.version}if(b.browser.webkit)b.browser.safari=true;if(Ha)b.inArray=function(a,c){return Ha.call(c,a)};D=b(m);if(m.addEventListener)ga=function(){m.removeEventListener("DOMContentLoaded",ga,false);b.ready()};else if(m.attachEvent)ga=function(){if(m.readyState==="complete"){m.detachEvent("onreadystatechange",ga);b.ready()}};(function(){b.support={};var a=m.documentElement,c=m.createElement("script"),d=m.createElement("div"),
f="script"+u();d.style.display="none";d.innerHTML="   <link/><table></table><a href='/a' style='color:red;float:left;opacity:.55;'>a</a><input type='checkbox'/>";var e=d.getElementsByTagName("*"),i=d.getElementsByTagName("a")[0];if(!(!e||!e.length||!i)){b.support={leadingWhitespace:d.firstChild.nodeType===3,tbody:!d.getElementsByTagName("tbody").length,htmlSerialize:!!d.getElementsByTagName("link").length,style:/red/.test(i.getAttribute("style")),hrefNormalized:i.getAttribute("href")==="/a",opacity:/^0.55$/.test(i.style.opacity),
cssFloat:!!i.style.cssFloat,checkOn:d.getElementsByTagName("input")[0].value==="on",optSelected:m.createElement("select").appendChild(m.createElement("option")).selected,parentNode:d.removeChild(d.appendChild(m.createElement("div"))).parentNode===null,deleteExpando:true,checkClone:false,scriptEval:false,noCloneEvent:true,boxModel:null};c.type="text/javascript";try{c.appendChild(m.createTextNode("window."+f+"=1;"))}catch(j){}a.insertBefore(c,a.firstChild);if(A[f]){b.support.scriptEval=true;delete A[f]}try{delete c.test}catch(r){b.support.deleteExpando=
false}a.removeChild(c);if(d.attachEvent&&d.fireEvent){d.attachEvent("onclick",function k(){b.support.noCloneEvent=false;d.detachEvent("onclick",k)});d.cloneNode(true).fireEvent("onclick")}d=m.createElement("div");d.innerHTML="<input type='radio' name='radiotest' checked='checked'/>";a=m.createDocumentFragment();a.appendChild(d.firstChild);b.support.checkClone=a.cloneNode(true).cloneNode(true).lastChild.checked;b(function(){var k=m.createElement("div");k.style.width=k.style.paddingLeft="1px";m.body.appendChild(k);
b.boxModel=b.support.boxModel=k.offsetWidth===2;m.body.removeChild(k).style.display="none"});a=function(k){var q=m.createElement("div");k="on"+k;var w=k in q;if(!w){q.setAttribute(k,"return;");w=typeof q[k]==="function"}return w};b.support.submitBubbles=a("submit");b.support.changeBubbles=a("change");a=c=d=e=i=null}})();b.props={"for":"htmlFor","class":"className",readonly:"readOnly",maxlength:"maxLength",cellspacing:"cellSpacing",rowspan:"rowSpan",colspan:"colSpan",tabindex:"tabIndex",usemap:"useMap",
frameborder:"frameBorder"};var ca="jQuery"+u(),Za=0,Ia={};b.extend({cache:{},expando:ca,noData:{embed:true,object:true,applet:true},data:function(a,c,d){if(!(a.nodeName&&b.noData[a.nodeName.toLowerCase()])){a=a==A?Ia:a;var f=a[ca],e=b.cache;if(!f&&typeof c==="string"&&d===z)return null;f||(f=++Za);if(typeof c==="object"){a[ca]=f;e[f]=b.extend(true,{},c)}else if(!e[f]){a[ca]=f;e[f]={}}a=e[f];if(d!==z)a[c]=d;return typeof c==="string"?a[c]:a}},removeData:function(a,c){if(!(a.nodeName&&b.noData[a.nodeName.toLowerCase()])){a=
a==A?Ia:a;var d=a[ca],f=b.cache,e=f[d];if(c){if(e){delete e[c];b.isEmptyObject(e)&&b.removeData(a)}}else{if(b.support.deleteExpando)delete a[b.expando];else a.removeAttribute&&a.removeAttribute(b.expando);delete f[d]}}}});b.fn.extend({data:function(a,c){if(typeof a==="undefined"&&this.length)return b.data(this[0]);else if(typeof a==="object")return this.each(function(){b.data(this,a)});var d=a.split(".");d[1]=d[1]?"."+d[1]:"";if(c===z){var f=this.triggerHandler("getData"+d[1]+"!",[d[0]]);if(f===z&&
this.length)f=b.data(this[0],a);return f===z&&d[1]?this.data(d[0]):f}else return this.trigger("setData"+d[1]+"!",[d[0],c]).each(function(){b.data(this,a,c)})},removeData:function(a){return this.each(function(){b.removeData(this,a)})}});b.extend({queue:function(a,c,d){if(a){c=(c||"fx")+"queue";var f=b.data(a,c);if(!d)return f||[];if(!f||b.isArray(d))f=b.data(a,c,b.makeArray(d));else f.push(d);return f}},dequeue:function(a,c){c=c||"fx";var d=b.queue(a,c),f=d.shift();if(f==="inprogress")f=d.shift();
if(f){c==="fx"&&d.unshift("inprogress");f.call(a,function(){b.dequeue(a,c)})}}});b.fn.extend({queue:function(a,c){if(typeof a!=="string"){c=a;a="fx"}if(c===z)return b.queue(this[0],a);return this.each(function(){var d=b.queue(this,a,c);a==="fx"&&d[0]!=="inprogress"&&b.dequeue(this,a)})},dequeue:function(a){return this.each(function(){b.dequeue(this,a)})},delay:function(a,c){a=b.fx?b.fx.speeds[a]||a:a;c=c||"fx";return this.queue(c,function(){var d=this;setTimeout(function(){b.dequeue(d,c)},a)})},clearQueue:function(a){return this.queue(a||
"fx",[])}});var Ja=/[\n\t]/g,ua=/\s+/,$a=/\r/g,ab=/href|src|style/,bb=/(button|input)/i,cb=/(button|input|object|select|textarea)/i,db=/^(a|area)$/i,Ka=/radio|checkbox/;b.fn.extend({attr:function(a,c){return o(this,a,c,true,b.attr)},removeAttr:function(a){return this.each(function(){b.attr(this,a,"");this.nodeType===1&&this.removeAttribute(a)})},addClass:function(a){if(b.isFunction(a))return this.each(function(q){var w=b(this);w.addClass(a.call(this,q,w.attr("class")))});if(a&&typeof a==="string")for(var c=
(a||"").split(ua),d=0,f=this.length;d<f;d++){var e=this[d];if(e.nodeType===1)if(e.className){for(var i=" "+e.className+" ",j=e.className,r=0,k=c.length;r<k;r++)if(i.indexOf(" "+c[r]+" ")<0)j+=" "+c[r];e.className=b.trim(j)}else e.className=a}return this},removeClass:function(a){if(b.isFunction(a))return this.each(function(k){var q=b(this);q.removeClass(a.call(this,k,q.attr("class")))});if(a&&typeof a==="string"||a===z)for(var c=(a||"").split(ua),d=0,f=this.length;d<f;d++){var e=this[d];if(e.nodeType===
1&&e.className)if(a){for(var i=(" "+e.className+" ").replace(Ja," "),j=0,r=c.length;j<r;j++)i=i.replace(" "+c[j]+" "," ");e.className=b.trim(i)}else e.className=""}return this},toggleClass:function(a,c){var d=typeof a,f=typeof c==="boolean";if(b.isFunction(a))return this.each(function(e){var i=b(this);i.toggleClass(a.call(this,e,i.attr("class"),c),c)});return this.each(function(){if(d==="string")for(var e,i=0,j=b(this),r=c,k=a.split(ua);e=k[i++];){r=f?r:!j.hasClass(e);j[r?"addClass":"removeClass"](e)}else if(d===
"undefined"||d==="boolean"){this.className&&b.data(this,"__className__",this.className);this.className=this.className||a===false?"":b.data(this,"__className__")||""}})},hasClass:function(a){a=" "+a+" ";for(var c=0,d=this.length;c<d;c++)if((" "+this[c].className+" ").replace(Ja," ").indexOf(a)>-1)return true;return false},val:function(a){if(a===z){var c=this[0];if(c){if(b.nodeName(c,"option"))return(c.attributes.value||{}).specified?c.value:c.text;if(b.nodeName(c,"select")){var d=c.selectedIndex,f=
[],e=c.options;c=c.type==="select-one";if(d<0)return null;var i=c?d:0;for(d=c?d+1:e.length;i<d;i++){var j=e[i];if(j.selected){a=b(j).val();if(c)return a;f.push(a)}}return f}if(Ka.test(c.type)&&!b.support.checkOn)return c.getAttribute("value")===null?"on":c.value;return(c.value||"").replace($a,"")}return z}var r=b.isFunction(a);return this.each(function(k){var q=b(this),w=a;if(this.nodeType===1){if(r)w=a.call(this,k,q.val());if(typeof w==="number")w+="";if(b.isArray(w)&&Ka.test(this.type))this.checked=
b.inArray(q.val(),w)>=0;else if(b.nodeName(this,"select")){var E=b.makeArray(w);b("option",this).each(function(){this.selected=b.inArray(b(this).val(),E)>=0});if(!E.length)this.selectedIndex=-1}else this.value=w}})}});b.extend({attrFn:{val:true,css:true,html:true,text:true,data:true,width:true,height:true,offset:true},attr:function(a,c,d,f){if(!a||a.nodeType===3||a.nodeType===8)return z;if(f&&c in b.attrFn)return b(a)[c](d);f=a.nodeType!==1||!b.isXMLDoc(a);var e=d!==z;c=f&&b.props[c]||c;if(a.nodeType===
1){var i=ab.test(c);if(c in a&&f&&!i){if(e){c==="type"&&bb.test(a.nodeName)&&a.parentNode&&b.error("type property can't be changed");a[c]=d}if(b.nodeName(a,"form")&&a.getAttributeNode(c))return a.getAttributeNode(c).nodeValue;if(c==="tabIndex")return(c=a.getAttributeNode("tabIndex"))&&c.specified?c.value:cb.test(a.nodeName)||db.test(a.nodeName)&&a.href?0:z;return a[c]}if(!b.support.style&&f&&c==="style"){if(e)a.style.cssText=""+d;return a.style.cssText}e&&a.setAttribute(c,""+d);a=!b.support.hrefNormalized&&
f&&i?a.getAttribute(c,2):a.getAttribute(c);return a===null?z:a}return b.style(a,c,d)}});var la=/\.(.*)$/,eb=function(a){return a.replace(/[^\w\s\.\|`]/g,function(c){return"\\"+c})};b.event={add:function(a,c,d,f){if(!(a.nodeType===3||a.nodeType===8)){if(a.setInterval&&a!==A&&!a.frameElement)a=A;var e,i;if(d.handler){e=d;d=e.handler}if(!d.guid)d.guid=b.guid++;if(i=b.data(a)){var j=i.events=i.events||{},r=i.handle;if(!r)i.handle=r=function(){return typeof b!=="undefined"&&!b.event.triggered?b.event.handle.apply(r.elem,
arguments):z};r.elem=a;c=c.split(" ");for(var k,q=0,w;k=c[q++];){i=e?b.extend({},e):{handler:d,data:f};if(k.indexOf(".")>-1){w=k.split(".");k=w.shift();i.namespace=w.slice(0).sort().join(".")}else{w=[];i.namespace=""}i.type=k;i.guid=d.guid;var E=j[k],K=b.event.special[k]||{};if(!E){E=j[k]=[];if(!K.setup||K.setup.call(a,f,w,r)===false)if(a.addEventListener)a.addEventListener(k,r,false);else a.attachEvent&&a.attachEvent("on"+k,r)}if(K.add){K.add.call(a,i);if(!i.handler.guid)i.handler.guid=d.guid}E.push(i);
b.event.global[k]=true}a=null}}},global:{},remove:function(a,c,d,f){if(!(a.nodeType===3||a.nodeType===8)){var e,i=0,j,r,k,q,w,E,K=b.data(a),S=K&&K.events;if(K&&S){if(c&&c.type){d=c.handler;c=c.type}if(!c||typeof c==="string"&&c.charAt(0)==="."){c=c||"";for(e in S)b.event.remove(a,e+c)}else{for(c=c.split(" ");e=c[i++];){q=e;j=e.indexOf(".")<0;r=[];if(!j){r=e.split(".");e=r.shift();k=new RegExp("(^|\\.)"+b.map(r.slice(0).sort(),eb).join("\\.(?:.*\\.)?")+"(\\.|$)")}if(w=S[e])if(d){q=b.event.special[e]||
{};for(Q=f||0;Q<w.length;Q++){E=w[Q];if(d.guid===E.guid){if(j||k.test(E.namespace)){f==null&&w.splice(Q--,1);q.remove&&q.remove.call(a,E)}if(f!=null)break}}if(w.length===0||f!=null&&w.length===1){if(!q.teardown||q.teardown.call(a,r)===false)La(a,e,K.handle);delete S[e]}}else for(var Q=0;Q<w.length;Q++){E=w[Q];if(j||k.test(E.namespace)){b.event.remove(a,q,E.handler,Q);w.splice(Q--,1)}}}if(b.isEmptyObject(S)){if(c=K.handle)c.elem=null;delete K.events;delete K.handle;b.isEmptyObject(K)&&b.removeData(a)}}}}},
trigger:function(a,c,d,f){var e=a.type||a;if(!f){a=typeof a==="object"?a[ca]?a:b.extend(b.Event(e),a):b.Event(e);if(e.indexOf("!")>=0){a.type=e=e.slice(0,-1);a.exclusive=true}if(!d){a.stopPropagation();b.event.global[e]&&b.each(b.cache,function(){this.events&&this.events[e]&&b.event.trigger(a,c,this.handle.elem)})}if(!d||d.nodeType===3||d.nodeType===8)return z;a.result=z;a.target=d;c=b.makeArray(c);c.unshift(a)}a.currentTarget=d;(f=b.data(d,"handle"))&&f.apply(d,c);f=d.parentNode||d.ownerDocument;
try{if(!(d&&d.nodeName&&b.noData[d.nodeName.toLowerCase()]))if(d["on"+e]&&d["on"+e].apply(d,c)===false)a.result=false}catch(i){}if(!a.isPropagationStopped()&&f)b.event.trigger(a,c,f,true);else if(!a.isDefaultPrevented()){f=a.target;var j,r=b.nodeName(f,"a")&&e==="click",k=b.event.special[e]||{};if((!k._default||k._default.call(d,a)===false)&&!r&&!(f&&f.nodeName&&b.noData[f.nodeName.toLowerCase()])){try{if(f[e]){if(j=f["on"+e])f["on"+e]=null;b.event.triggered=true;f[e]()}}catch(q){}if(j)f["on"+e]=
j;b.event.triggered=false}}},handle:function(a){var c,d,f,e;a=arguments[0]=b.event.fix(a||A.event);a.currentTarget=this;c=a.type.indexOf(".")<0&&!a.exclusive;if(!c){d=a.type.split(".");a.type=d.shift();f=new RegExp("(^|\\.)"+d.slice(0).sort().join("\\.(?:.*\\.)?")+"(\\.|$)")}e=b.data(this,"events");d=e[a.type];if(e&&d){d=d.slice(0);e=0;for(var i=d.length;e<i;e++){var j=d[e];if(c||f.test(j.namespace)){a.handler=j.handler;a.data=j.data;a.handleObj=j;j=j.handler.apply(this,arguments);if(j!==z){a.result=
j;if(j===false){a.preventDefault();a.stopPropagation()}}if(a.isImmediatePropagationStopped())break}}}return a.result},props:"altKey attrChange attrName bubbles button cancelable charCode clientX clientY ctrlKey currentTarget data detail eventPhase fromElement handler keyCode layerX layerY metaKey newValue offsetX offsetY originalTarget pageX pageY prevValue relatedNode relatedTarget screenX screenY shiftKey srcElement target toElement view wheelDelta which".split(" "),fix:function(a){if(a[ca])return a;
var c=a;a=b.Event(c);for(var d=this.props.length,f;d;){f=this.props[--d];a[f]=c[f]}if(!a.target)a.target=a.srcElement||m;if(a.target.nodeType===3)a.target=a.target.parentNode;if(!a.relatedTarget&&a.fromElement)a.relatedTarget=a.fromElement===a.target?a.toElement:a.fromElement;if(a.pageX==null&&a.clientX!=null){c=m.documentElement;d=m.body;a.pageX=a.clientX+(c&&c.scrollLeft||d&&d.scrollLeft||0)-(c&&c.clientLeft||d&&d.clientLeft||0);a.pageY=a.clientY+(c&&c.scrollTop||d&&d.scrollTop||0)-(c&&c.clientTop||
d&&d.clientTop||0)}if(!a.which&&(a.charCode||a.charCode===0?a.charCode:a.keyCode))a.which=a.charCode||a.keyCode;if(!a.metaKey&&a.ctrlKey)a.metaKey=a.ctrlKey;if(!a.which&&a.button!==z)a.which=a.button&1?1:a.button&2?3:a.button&4?2:0;return a},guid:1E8,proxy:b.proxy,special:{ready:{setup:b.bindReady,teardown:b.noop},live:{add:function(a){b.event.add(this,a.origType,b.extend({},a,{handler:U}))},remove:function(a){var c=true,d=a.origType.replace(la,"");b.each(b.data(this,"events").live||[],function(){if(d===
this.origType.replace(la,""))return c=false});c&&b.event.remove(this,a.origType,U)}},beforeunload:{setup:function(a,c,d){if(this.setInterval)this.onbeforeunload=d;return false},teardown:function(a,c){if(this.onbeforeunload===c)this.onbeforeunload=null}}}};var La=m.removeEventListener?function(a,c,d){a.removeEventListener(c,d,false)}:function(a,c,d){a.detachEvent("on"+c,d)};b.Event=function(a){if(!this.preventDefault)return new b.Event(a);if(a&&a.type){this.originalEvent=a;this.type=a.type}else this.type=
a;this.timeStamp=u();this[ca]=true};b.Event.prototype={preventDefault:function(){this.isDefaultPrevented=y;var a=this.originalEvent;if(a){a.preventDefault&&a.preventDefault();a.returnValue=false}},stopPropagation:function(){this.isPropagationStopped=y;var a=this.originalEvent;if(a){a.stopPropagation&&a.stopPropagation();a.cancelBubble=true}},stopImmediatePropagation:function(){this.isImmediatePropagationStopped=y;this.stopPropagation()},isDefaultPrevented:H,isPropagationStopped:H,isImmediatePropagationStopped:H};
var Ma=function(a){var c=a.relatedTarget;try{for(;c&&c!==this;)c=c.parentNode;if(c!==this){a.type=a.data;b.event.handle.apply(this,arguments)}}catch(d){}},Na=function(a){a.type=a.data;b.event.handle.apply(this,arguments)};b.each({mouseenter:"mouseover",mouseleave:"mouseout"},function(a,c){b.event.special[a]={setup:function(d){b.event.add(this,c,d&&d.selector?Na:Ma,a)},teardown:function(d){b.event.remove(this,c,d&&d.selector?Na:Ma)}}});if(!b.support.submitBubbles)b.event.special.submit={setup:function(){if(this.nodeName.toLowerCase()!==
"form"){b.event.add(this,"click.specialSubmit",function(a){var c=a.target,d=c.type;if((d==="submit"||d==="image")&&b(c).closest("form").length)return B("submit",this,arguments)});b.event.add(this,"keypress.specialSubmit",function(a){var c=a.target,d=c.type;if((d==="text"||d==="password")&&b(c).closest("form").length&&a.keyCode===13)return B("submit",this,arguments)})}else return false},teardown:function(){b.event.remove(this,".specialSubmit")}};if(!b.support.changeBubbles){var va=/textarea|input|select/i,
wa,Oa=function(a){var c=a.type,d=a.value;if(c==="radio"||c==="checkbox")d=a.checked;else if(c==="select-multiple")d=a.selectedIndex>-1?b.map(a.options,function(f){return f.selected}).join("-"):"";else if(a.nodeName.toLowerCase()==="select")d=a.selectedIndex;return d},xa=function(a,c){var d=a.target,f,e;if(!(!va.test(d.nodeName)||d.readOnly)){f=b.data(d,"_change_data");e=Oa(d);if(a.type!=="focusout"||d.type!=="radio")b.data(d,"_change_data",e);if(!(f===z||e===f))if(f!=null||e){a.type="change";return b.event.trigger(a,
c,d)}}};b.event.special.change={filters:{focusout:xa,click:function(a){var c=a.target,d=c.type;if(d==="radio"||d==="checkbox"||c.nodeName.toLowerCase()==="select")return xa.call(this,a)},keydown:function(a){var c=a.target,d=c.type;if(a.keyCode===13&&c.nodeName.toLowerCase()!=="textarea"||a.keyCode===32&&(d==="checkbox"||d==="radio")||d==="select-multiple")return xa.call(this,a)},beforeactivate:function(a){a=a.target;b.data(a,"_change_data",Oa(a))}},setup:function(){if(this.type==="file")return false;
for(var a in wa)b.event.add(this,a+".specialChange",wa[a]);return va.test(this.nodeName)},teardown:function(){b.event.remove(this,".specialChange");return va.test(this.nodeName)}};wa=b.event.special.change.filters}m.addEventListener&&b.each({focus:"focusin",blur:"focusout"},function(a,c){function d(f){f=b.event.fix(f);f.type=c;return b.event.handle.call(this,f)}b.event.special[c]={setup:function(){this.addEventListener(a,d,true)},teardown:function(){this.removeEventListener(a,d,true)}}});b.each(["bind",
"one"],function(a,c){b.fn[c]=function(d,f,e){if(typeof d==="object"){for(var i in d)this[c](i,f,d[i],e);return this}if(b.isFunction(f)){e=f;f=z}var j=c==="one"?b.proxy(e,function(k){b(this).unbind(k,j);return e.apply(this,arguments)}):e;if(d==="unload"&&c!=="one")this.one(d,f,e);else{i=0;for(var r=this.length;i<r;i++)b.event.add(this[i],d,j,f)}return this}});b.fn.extend({unbind:function(a,c){if(typeof a==="object"&&!a.preventDefault)for(var d in a)this.unbind(d,a[d]);else{d=0;for(var f=this.length;d<
f;d++)b.event.remove(this[d],a,c)}return this},delegate:function(a,c,d,f){return this.live(c,d,f,a)},undelegate:function(a,c,d){return arguments.length===0?this.unbind("live"):this.die(c,null,d,a)},trigger:function(a,c){return this.each(function(){b.event.trigger(a,c,this)})},triggerHandler:function(a,c){if(this[0]){a=b.Event(a);a.preventDefault();a.stopPropagation();b.event.trigger(a,c,this[0]);return a.result}},toggle:function(a){for(var c=arguments,d=1;d<c.length;)b.proxy(a,c[d++]);return this.click(b.proxy(a,
function(f){var e=(b.data(this,"lastToggle"+a.guid)||0)%d;b.data(this,"lastToggle"+a.guid,e+1);f.preventDefault();return c[e].apply(this,arguments)||false}))},hover:function(a,c){return this.mouseenter(a).mouseleave(c||a)}});var Pa={focus:"focusin",blur:"focusout",mouseenter:"mouseover",mouseleave:"mouseout"};b.each(["live","die"],function(a,c){b.fn[c]=function(d,f,e,i){var j,r=0,k,q,w=i||this.selector,E=i?this:b(this.context);if(b.isFunction(f)){e=f;f=z}for(d=(d||"").split(" ");(j=d[r++])!=null;){i=
la.exec(j);k="";if(i){k=i[0];j=j.replace(la,"")}if(j==="hover")d.push("mouseenter"+k,"mouseleave"+k);else{q=j;if(j==="focus"||j==="blur"){d.push(Pa[j]+k);j+=k}else j=(Pa[j]||j)+k;c==="live"?E.each(function(){b.event.add(this,N(j,w),{data:f,selector:w,handler:e,origType:j,origHandler:e,preType:q})}):E.unbind(N(j,w),e)}}return this}});b.each("blur focus focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup error".split(" "),
function(a,c){b.fn[c]=function(d){return d?this.bind(c,d):this.trigger(c)};if(b.attrFn)b.attrFn[c]=true});A.attachEvent&&!A.addEventListener&&A.attachEvent("onunload",function(){for(var a in b.cache)if(b.cache[a].handle)try{b.event.remove(b.cache[a].handle.elem)}catch(c){}});(function(){function a(g){for(var h="",l,p=0;g[p];p++){l=g[p];if(l.nodeType===3||l.nodeType===4)h+=l.nodeValue;else if(l.nodeType!==8)h+=a(l.childNodes)}return h}function c(g,h,l,p,t,s){t=0;for(var G=p.length;t<G;t++){var C=p[t];
if(C){C=C[g];for(var J=false;C;){if(C.sizcache===l){J=p[C.sizset];break}if(C.nodeType===1&&!s){C.sizcache=l;C.sizset=t}if(C.nodeName.toLowerCase()===h){J=C;break}C=C[g]}p[t]=J}}}function d(g,h,l,p,t,s){t=0;for(var G=p.length;t<G;t++){var C=p[t];if(C){C=C[g];for(var J=false;C;){if(C.sizcache===l){J=p[C.sizset];break}if(C.nodeType===1){if(!s){C.sizcache=l;C.sizset=t}if(typeof h!=="string"){if(C===h){J=true;break}}else if(k.filter(h,[C]).length>0){J=C;break}}C=C[g]}p[t]=J}}}var f=/((?:\((?:\([^()]+\)|[^()]+)+\)|\[(?:\[[^[\]]*\]|['"][^'"]*['"]|[^[\]'"]+)+\]|\\.|[^ >+~,(\[\\]+)+|[>+~])(\s*,\s*)?((?:.|\r|\n)*)/g,
e=0,i=Object.prototype.toString,j=false,r=true;[0,0].sort(function(){r=false;return 0});var k=function(g,h,l,p){l=l||[];var t=h=h||m;if(h.nodeType!==1&&h.nodeType!==9)return[];if(!g||typeof g!=="string")return l;for(var s=[],G,C,J,na,da=true,ha=I(h),ea=g;(f.exec(""),G=f.exec(ea))!==null;){ea=G[3];s.push(G[1]);if(G[2]){na=G[3];break}}if(s.length>1&&w.exec(g))if(s.length===2&&q.relative[s[0]])C=ya(s[0]+s[1],h);else for(C=q.relative[s[0]]?[h]:k(s.shift(),h);s.length;){g=s.shift();if(q.relative[g])g+=
s.shift();C=ya(g,C)}else{if(!p&&s.length>1&&h.nodeType===9&&!ha&&q.match.ID.test(s[0])&&!q.match.ID.test(s[s.length-1])){G=k.find(s.shift(),h,ha);h=G.expr?k.filter(G.expr,G.set)[0]:G.set[0]}if(h){G=p?{expr:s.pop(),set:K(p)}:k.find(s.pop(),s.length===1&&(s[0]==="~"||s[0]==="+")&&h.parentNode?h.parentNode:h,ha);C=G.expr?k.filter(G.expr,G.set):G.set;if(s.length>0)J=K(C);else da=false;for(;s.length;){var Z=s.pop();G=Z;if(q.relative[Z])G=s.pop();else Z="";if(G==null)G=h;q.relative[Z](J,G,ha)}}else J=[]}J||
(J=C);J||k.error(Z||g);if(i.call(J)==="[object Array]")if(da)if(h&&h.nodeType===1)for(g=0;J[g]!=null;g++){if(J[g]&&(J[g]===true||J[g].nodeType===1&&$(h,J[g])))l.push(C[g])}else for(g=0;J[g]!=null;g++)J[g]&&J[g].nodeType===1&&l.push(C[g]);else l.push.apply(l,J);else K(J,l);if(na){k(na,t,l,p);k.uniqueSort(l)}return l};k.uniqueSort=function(g){if(Q){j=r;g.sort(Q);if(j)for(var h=1;h<g.length;h++)g[h]===g[h-1]&&g.splice(h--,1)}return g};k.matches=function(g,h){return k(g,null,null,h)};k.find=function(g,
h,l){var p,t;if(!g)return[];for(var s=0,G=q.order.length;s<G;s++){var C=q.order[s];if(t=q.leftMatch[C].exec(g)){var J=t[1];t.splice(1,1);if(J.substr(J.length-1)!=="\\"){t[1]=(t[1]||"").replace(/\\/g,"");p=q.find[C](t,h,l);if(p!=null){g=g.replace(q.match[C],"");break}}}}p||(p=h.getElementsByTagName("*"));return{set:p,expr:g}};k.filter=function(g,h,l,p){for(var t=g,s=[],G=h,C,J,na=h&&h[0]&&I(h[0]);g&&h.length;){for(var da in q.filter)if((C=q.leftMatch[da].exec(g))!=null&&C[2]){var ha=q.filter[da],ea,
Z;Z=C[1];J=false;C.splice(1,1);if(Z.substr(Z.length-1)!=="\\"){if(G===s)s=[];if(q.preFilter[da])if(C=q.preFilter[da](C,G,l,s,p,na)){if(C===true)continue}else J=ea=true;if(C)for(var oa=0;(Z=G[oa])!=null;oa++)if(Z){ea=ha(Z,C,oa,G);var Qa=p^!!ea;if(l&&ea!=null)if(Qa)J=true;else G[oa]=false;else if(Qa){s.push(Z);J=true}}if(ea!==z){l||(G=s);g=g.replace(q.match[da],"");if(!J)return[];break}}}if(g===t)if(J==null)k.error(g);else break;t=g}return G};k.error=function(g){throw"Syntax error, unrecognized expression: "+
g;};var q=k.selectors={order:["ID","NAME","TAG"],match:{ID:/#((?:[\w\u00c0-\uFFFF-]|\\.)+)/,CLASS:/\.((?:[\w\u00c0-\uFFFF-]|\\.)+)/,NAME:/\[name=['"]*((?:[\w\u00c0-\uFFFF-]|\\.)+)['"]*\]/,ATTR:/\[\s*((?:[\w\u00c0-\uFFFF-]|\\.)+)\s*(?:(\S?=)\s*(['"]*)(.*?)\3|)\s*\]/,TAG:/^((?:[\w\u00c0-\uFFFF\*-]|\\.)+)/,CHILD:/:(only|nth|last|first)-child(?:\((even|odd|[\dn+-]*)\))?/,POS:/:(nth|eq|gt|lt|first|last|even|odd)(?:\((\d*)\))?(?=[^-]|$)/,PSEUDO:/:((?:[\w\u00c0-\uFFFF-]|\\.)+)(?:\((['"]?)((?:\([^\)]+\)|[^\(\)]*)+)\2\))?/},
leftMatch:{},attrMap:{"class":"className","for":"htmlFor"},attrHandle:{href:function(g){return g.getAttribute("href")}},relative:{"+":function(g,h){var l=typeof h==="string",p=l&&!/\W/.test(h);l=l&&!p;if(p)h=h.toLowerCase();p=0;for(var t=g.length,s;p<t;p++)if(s=g[p]){for(;(s=s.previousSibling)&&s.nodeType!==1;);g[p]=l||s&&s.nodeName.toLowerCase()===h?s||false:s===h}l&&k.filter(h,g,true)},">":function(g,h){var l=typeof h==="string";if(l&&!/\W/.test(h)){h=h.toLowerCase();for(var p=0,t=g.length;p<t;p++){var s=
g[p];if(s){l=s.parentNode;g[p]=l.nodeName.toLowerCase()===h?l:false}}}else{p=0;for(t=g.length;p<t;p++)if(s=g[p])g[p]=l?s.parentNode:s.parentNode===h;l&&k.filter(h,g,true)}},"":function(g,h,l){var p=e++,t=d;if(typeof h==="string"&&!/\W/.test(h)){var s=h=h.toLowerCase();t=c}t("parentNode",h,p,g,s,l)},"~":function(g,h,l){var p=e++,t=d;if(typeof h==="string"&&!/\W/.test(h)){var s=h=h.toLowerCase();t=c}t("previousSibling",h,p,g,s,l)}},find:{ID:function(g,h,l){if(typeof h.getElementById!=="undefined"&&
!l)return(g=h.getElementById(g[1]))?[g]:[]},NAME:function(g,h){if(typeof h.getElementsByName!=="undefined"){var l=[];h=h.getElementsByName(g[1]);for(var p=0,t=h.length;p<t;p++)h[p].getAttribute("name")===g[1]&&l.push(h[p]);return l.length===0?null:l}},TAG:function(g,h){return h.getElementsByTagName(g[1])}},preFilter:{CLASS:function(g,h,l,p,t,s){g=" "+g[1].replace(/\\/g,"")+" ";if(s)return g;s=0;for(var G;(G=h[s])!=null;s++)if(G)if(t^(G.className&&(" "+G.className+" ").replace(/[\t\n]/g," ").indexOf(g)>=
0))l||p.push(G);else if(l)h[s]=false;return false},ID:function(g){return g[1].replace(/\\/g,"")},TAG:function(g){return g[1].toLowerCase()},CHILD:function(g){if(g[1]==="nth"){var h=/(-?)(\d*)n((?:\+|-)?\d*)/.exec(g[2]==="even"&&"2n"||g[2]==="odd"&&"2n+1"||!/\D/.test(g[2])&&"0n+"+g[2]||g[2]);g[2]=h[1]+(h[2]||1)-0;g[3]=h[3]-0}g[0]=e++;return g},ATTR:function(g,h,l,p,t,s){h=g[1].replace(/\\/g,"");if(!s&&q.attrMap[h])g[1]=q.attrMap[h];if(g[2]==="~=")g[4]=" "+g[4]+" ";return g},PSEUDO:function(g,h,l,p,
t){if(g[1]==="not")if((f.exec(g[3])||"").length>1||/^\w/.test(g[3]))g[3]=k(g[3],null,null,h);else{g=k.filter(g[3],h,l,true^t);l||p.push.apply(p,g);return false}else if(q.match.POS.test(g[0])||q.match.CHILD.test(g[0]))return true;return g},POS:function(g){g.unshift(true);return g}},filters:{enabled:function(g){return g.disabled===false&&g.type!=="hidden"},disabled:function(g){return g.disabled===true},checked:function(g){return g.checked===true},selected:function(g){return g.selected===true},parent:function(g){return!!g.firstChild},
empty:function(g){return!g.firstChild},has:function(g,h,l){return!!k(l[3],g).length},header:function(g){return/h\d/i.test(g.nodeName)},text:function(g){return"text"===g.type},radio:function(g){return"radio"===g.type},checkbox:function(g){return"checkbox"===g.type},file:function(g){return"file"===g.type},password:function(g){return"password"===g.type},submit:function(g){return"submit"===g.type},image:function(g){return"image"===g.type},reset:function(g){return"reset"===g.type},button:function(g){return"button"===
g.type||g.nodeName.toLowerCase()==="button"},input:function(g){return/input|select|textarea|button/i.test(g.nodeName)}},setFilters:{first:function(g,h){return h===0},last:function(g,h,l,p){return h===p.length-1},even:function(g,h){return h%2===0},odd:function(g,h){return h%2===1},lt:function(g,h,l){return h<l[3]-0},gt:function(g,h,l){return h>l[3]-0},nth:function(g,h,l){return l[3]-0===h},eq:function(g,h,l){return l[3]-0===h}},filter:{PSEUDO:function(g,h,l,p){var t=h[1],s=q.filters[t];if(s)return s(g,
l,h,p);else if(t==="contains")return(g.textContent||g.innerText||a([g])||"").indexOf(h[3])>=0;else if(t==="not"){h=h[3];l=0;for(p=h.length;l<p;l++)if(h[l]===g)return false;return true}else k.error("Syntax error, unrecognized expression: "+t)},CHILD:function(g,h){var l=h[1],p=g;switch(l){case "only":case "first":for(;p=p.previousSibling;)if(p.nodeType===1)return false;if(l==="first")return true;p=g;case "last":for(;p=p.nextSibling;)if(p.nodeType===1)return false;return true;case "nth":l=h[2];var t=
h[3];if(l===1&&t===0)return true;h=h[0];var s=g.parentNode;if(s&&(s.sizcache!==h||!g.nodeIndex)){var G=0;for(p=s.firstChild;p;p=p.nextSibling)if(p.nodeType===1)p.nodeIndex=++G;s.sizcache=h}g=g.nodeIndex-t;return l===0?g===0:g%l===0&&g/l>=0}},ID:function(g,h){return g.nodeType===1&&g.getAttribute("id")===h},TAG:function(g,h){return h==="*"&&g.nodeType===1||g.nodeName.toLowerCase()===h},CLASS:function(g,h){return(" "+(g.className||g.getAttribute("class"))+" ").indexOf(h)>-1},ATTR:function(g,h){var l=
h[1];g=q.attrHandle[l]?q.attrHandle[l](g):g[l]!=null?g[l]:g.getAttribute(l);l=g+"";var p=h[2];h=h[4];return g==null?p==="!=":p==="="?l===h:p==="*="?l.indexOf(h)>=0:p==="~="?(" "+l+" ").indexOf(h)>=0:!h?l&&g!==false:p==="!="?l!==h:p==="^="?l.indexOf(h)===0:p==="$="?l.substr(l.length-h.length)===h:p==="|="?l===h||l.substr(0,h.length+1)===h+"-":false},POS:function(g,h,l,p){var t=q.setFilters[h[2]];if(t)return t(g,l,h,p)}}},w=q.match.POS;for(var E in q.match){q.match[E]=new RegExp(q.match[E].source+/(?![^\[]*\])(?![^\(]*\))/.source);
q.leftMatch[E]=new RegExp(/(^(?:.|\r|\n)*?)/.source+q.match[E].source.replace(/\\(\d+)/g,function(g,h){return"\\"+(h-0+1)}))}var K=function(g,h){g=Array.prototype.slice.call(g,0);if(h){h.push.apply(h,g);return h}return g};try{Array.prototype.slice.call(m.documentElement.childNodes,0)}catch(S){K=function(g,h){h=h||[];if(i.call(g)==="[object Array]")Array.prototype.push.apply(h,g);else if(typeof g.length==="number")for(var l=0,p=g.length;l<p;l++)h.push(g[l]);else for(l=0;g[l];l++)h.push(g[l]);return h}}var Q;
if(m.documentElement.compareDocumentPosition)Q=function(g,h){if(!g.compareDocumentPosition||!h.compareDocumentPosition){if(g==h)j=true;return g.compareDocumentPosition?-1:1}g=g.compareDocumentPosition(h)&4?-1:g===h?0:1;if(g===0)j=true;return g};else if("sourceIndex"in m.documentElement)Q=function(g,h){if(!g.sourceIndex||!h.sourceIndex){if(g==h)j=true;return g.sourceIndex?-1:1}g=g.sourceIndex-h.sourceIndex;if(g===0)j=true;return g};else if(m.createRange)Q=function(g,h){if(!g.ownerDocument||!h.ownerDocument){if(g==
h)j=true;return g.ownerDocument?-1:1}var l=g.ownerDocument.createRange(),p=h.ownerDocument.createRange();l.setStart(g,0);l.setEnd(g,0);p.setStart(h,0);p.setEnd(h,0);g=l.compareBoundaryPoints(Range.START_TO_END,p);if(g===0)j=true;return g};(function(){var g=m.createElement("div"),h="script"+(new Date).getTime();g.innerHTML="<a name='"+h+"'/>";var l=m.documentElement;l.insertBefore(g,l.firstChild);if(m.getElementById(h)){q.find.ID=function(p,t,s){if(typeof t.getElementById!=="undefined"&&!s)return(t=
t.getElementById(p[1]))?t.id===p[1]||typeof t.getAttributeNode!=="undefined"&&t.getAttributeNode("id").nodeValue===p[1]?[t]:z:[]};q.filter.ID=function(p,t){var s=typeof p.getAttributeNode!=="undefined"&&p.getAttributeNode("id");return p.nodeType===1&&s&&s.nodeValue===t}}l.removeChild(g);l=g=null})();(function(){var g=m.createElement("div");g.appendChild(m.createComment(""));if(g.getElementsByTagName("*").length>0)q.find.TAG=function(h,l){l=l.getElementsByTagName(h[1]);if(h[1]==="*"){h=[];for(var p=
0;l[p];p++)l[p].nodeType===1&&h.push(l[p]);l=h}return l};g.innerHTML="<a href='#'></a>";if(g.firstChild&&typeof g.firstChild.getAttribute!=="undefined"&&g.firstChild.getAttribute("href")!=="#")q.attrHandle.href=function(h){return h.getAttribute("href",2)};g=null})();m.querySelectorAll&&function(){var g=k,h=m.createElement("div");h.innerHTML="<p class='TEST'></p>";if(!(h.querySelectorAll&&h.querySelectorAll(".TEST").length===0)){k=function(p,t,s,G){t=t||m;if(!G&&t.nodeType===9&&!I(t))try{return K(t.querySelectorAll(p),
s)}catch(C){}return g(p,t,s,G)};for(var l in g)k[l]=g[l];h=null}}();(function(){var g=m.createElement("div");g.innerHTML="<div class='test e'></div><div class='test'></div>";if(!(!g.getElementsByClassName||g.getElementsByClassName("e").length===0)){g.lastChild.className="e";if(g.getElementsByClassName("e").length!==1){q.order.splice(1,0,"CLASS");q.find.CLASS=function(h,l,p){if(typeof l.getElementsByClassName!=="undefined"&&!p)return l.getElementsByClassName(h[1])};g=null}}})();var $=m.compareDocumentPosition?
function(g,h){return!!(g.compareDocumentPosition(h)&16)}:function(g,h){return g!==h&&(g.contains?g.contains(h):true)},I=function(g){return(g=(g?g.ownerDocument||g:0).documentElement)?g.nodeName!=="HTML":false},ya=function(g,h){var l=[],p="",t;for(h=h.nodeType?[h]:h;t=q.match.PSEUDO.exec(g);){p+=t[0];g=g.replace(q.match.PSEUDO,"")}g=q.relative[g]?g+"*":g;t=0;for(var s=h.length;t<s;t++)k(g,h[t],l);return k.filter(p,l)};b.find=k;b.expr=k.selectors;b.expr[":"]=b.expr.filters;b.unique=k.uniqueSort;b.text=
a;b.isXMLDoc=I;b.contains=$})();var fb=/Until$/,gb=/^(?:parents|prevUntil|prevAll)/,hb=/,/;ma=Array.prototype.slice;var Ra=function(a,c,d){if(b.isFunction(c))return b.grep(a,function(e,i){return!!c.call(e,i,e)===d});else if(c.nodeType)return b.grep(a,function(e){return e===c===d});else if(typeof c==="string"){var f=b.grep(a,function(e){return e.nodeType===1});if(P.test(c))return b.filter(c,f,!d);else c=b.filter(c,f)}return b.grep(a,function(e){return b.inArray(e,c)>=0===d})};b.fn.extend({find:function(a){for(var c=
this.pushStack("","find",a),d=0,f=0,e=this.length;f<e;f++){d=c.length;b.find(a,this[f],c);if(f>0)for(var i=d;i<c.length;i++)for(var j=0;j<d;j++)if(c[j]===c[i]){c.splice(i--,1);break}}return c},has:function(a){var c=b(a);return this.filter(function(){for(var d=0,f=c.length;d<f;d++)if(b.contains(this,c[d]))return true})},not:function(a){return this.pushStack(Ra(this,a,false),"not",a)},filter:function(a){return this.pushStack(Ra(this,a,true),"filter",a)},is:function(a){return!!a&&b.filter(a,this).length>
0},closest:function(a,c){if(b.isArray(a)){var d=[],f=this[0],e,i={},j;if(f&&a.length){e=0;for(var r=a.length;e<r;e++){j=a[e];i[j]||(i[j]=b.expr.match.POS.test(j)?b(j,c||this.context):j)}for(;f&&f.ownerDocument&&f!==c;){for(j in i){e=i[j];if(e.jquery?e.index(f)>-1:b(f).is(e)){d.push({selector:j,elem:f});delete i[j]}}f=f.parentNode}}return d}var k=b.expr.match.POS.test(a)?b(a,c||this.context):null;return this.map(function(q,w){for(;w&&w.ownerDocument&&w!==c;){if(k?k.index(w)>-1:b(w).is(a))return w;
w=w.parentNode}return null})},index:function(a){if(!a||typeof a==="string")return b.inArray(this[0],a?b(a):this.parent().children());return b.inArray(a.jquery?a[0]:a,this)},add:function(a,c){a=typeof a==="string"?b(a,c||this.context):b.makeArray(a);c=b.merge(this.get(),a);return this.pushStack(O(a[0])||O(c[0])?c:b.unique(c))},andSelf:function(){return this.add(this.prevObject)}});b.each({parent:function(a){return(a=a.parentNode)&&a.nodeType!==11?a:null},parents:function(a){return b.dir(a,"parentNode")},
parentsUntil:function(a,c,d){return b.dir(a,"parentNode",d)},next:function(a){return b.nth(a,2,"nextSibling")},prev:function(a){return b.nth(a,2,"previousSibling")},nextAll:function(a){return b.dir(a,"nextSibling")},prevAll:function(a){return b.dir(a,"previousSibling")},nextUntil:function(a,c,d){return b.dir(a,"nextSibling",d)},prevUntil:function(a,c,d){return b.dir(a,"previousSibling",d)},siblings:function(a){return b.sibling(a.parentNode.firstChild,a)},children:function(a){return b.sibling(a.firstChild)},
contents:function(a){return b.nodeName(a,"iframe")?a.contentDocument||a.contentWindow.document:b.makeArray(a.childNodes)}},function(a,c){b.fn[a]=function(d,f){var e=b.map(this,c,d);fb.test(a)||(f=d);if(f&&typeof f==="string")e=b.filter(f,e);e=this.length>1?b.unique(e):e;if((this.length>1||hb.test(f))&&gb.test(a))e=e.reverse();return this.pushStack(e,a,ma.call(arguments).join(","))}});b.extend({filter:function(a,c,d){if(d)a=":not("+a+")";return b.find.matches(a,c)},dir:function(a,c,d){var f=[];for(a=
a[c];a&&a.nodeType!==9&&(d===z||a.nodeType!==1||!b(a).is(d));){a.nodeType===1&&f.push(a);a=a[c]}return f},nth:function(a,c,d){c=c||1;for(var f=0;a;a=a[d])if(a.nodeType===1&&++f===c)break;return a},sibling:function(a,c){for(var d=[];a;a=a.nextSibling)a.nodeType===1&&a!==c&&d.push(a);return d}});var Sa=/ jQuery\d+="(?:\d+|null)"/g,pa=/^\s+/,Ta=/(<([\w:]+)[^>]*?)\/>/g,ib=/^(?:area|br|col|embed|hr|img|input|link|meta|param)$/i,Ua=/<([\w:]+)/,jb=/<tbody/i,kb=/<|&#?\w+;/,Ea=/<script|<object|<embed|<option|<style/i,
Fa=/checked\s*(?:[^=]|=\s*.checked.)/i,Va=function(a,c,d){return ib.test(d)?a:c+"></"+d+">"},aa={option:[1,"<select multiple='multiple'>","</select>"],legend:[1,"<fieldset>","</fieldset>"],thead:[1,"<table>","</table>"],tr:[2,"<table><tbody>","</tbody></table>"],td:[3,"<table><tbody><tr>","</tr></tbody></table>"],col:[2,"<table><tbody></tbody><colgroup>","</colgroup></table>"],area:[1,"<map>","</map>"],_default:[0,"",""]};aa.optgroup=aa.option;aa.tbody=aa.tfoot=aa.colgroup=aa.caption=aa.thead;aa.th=
aa.td;if(!b.support.htmlSerialize)aa._default=[1,"div<div>","</div>"];b.fn.extend({text:function(a){if(b.isFunction(a))return this.each(function(c){var d=b(this);d.text(a.call(this,c,d.text()))});if(typeof a!=="object"&&a!==z)return this.empty().append((this[0]&&this[0].ownerDocument||m).createTextNode(a));return b.text(this)},wrapAll:function(a){if(b.isFunction(a))return this.each(function(d){b(this).wrapAll(a.call(this,d))});if(this[0]){var c=b(a,this[0].ownerDocument).eq(0).clone(true);this[0].parentNode&&
c.insertBefore(this[0]);c.map(function(){for(var d=this;d.firstChild&&d.firstChild.nodeType===1;)d=d.firstChild;return d}).append(this)}return this},wrapInner:function(a){if(b.isFunction(a))return this.each(function(c){b(this).wrapInner(a.call(this,c))});return this.each(function(){var c=b(this),d=c.contents();d.length?d.wrapAll(a):c.append(a)})},wrap:function(a){return this.each(function(){b(this).wrapAll(a)})},unwrap:function(){return this.parent().each(function(){b.nodeName(this,"body")||b(this).replaceWith(this.childNodes)}).end()},
append:function(){return this.domManip(arguments,true,function(a){this.nodeType===1&&this.appendChild(a)})},prepend:function(){return this.domManip(arguments,true,function(a){this.nodeType===1&&this.insertBefore(a,this.firstChild)})},before:function(){if(this[0]&&this[0].parentNode)return this.domManip(arguments,false,function(c){this.parentNode.insertBefore(c,this)});else if(arguments.length){var a=b(arguments[0]);a.push.apply(a,this.toArray());return this.pushStack(a,"before",arguments)}},after:function(){if(this[0]&&
this[0].parentNode)return this.domManip(arguments,false,function(c){this.parentNode.insertBefore(c,this.nextSibling)});else if(arguments.length){var a=this.pushStack(this,"after",arguments);a.push.apply(a,b(arguments[0]).toArray());return a}},remove:function(a,c){for(var d=0,f;(f=this[d])!=null;d++)if(!a||b.filter(a,[f]).length){if(!c&&f.nodeType===1){b.cleanData(f.getElementsByTagName("*"));b.cleanData([f])}f.parentNode&&f.parentNode.removeChild(f)}return this},empty:function(){for(var a=0,c;(c=
this[a])!=null;a++)for(c.nodeType===1&&b.cleanData(c.getElementsByTagName("*"));c.firstChild;)c.removeChild(c.firstChild);return this},clone:function(a){var c=this.map(function(){if(!b.support.noCloneEvent&&!b.isXMLDoc(this)){var d=this.outerHTML,f=this.ownerDocument;if(!d){d=f.createElement("div");d.appendChild(this.cloneNode(true));d=d.innerHTML}return b.clean([d.replace(Sa,"").replace(/=([^="'>\s]+\/)>/g,'="$1">').replace(pa,"")],f)[0]}else return this.cloneNode(true)});if(a===true){M(this,c);
M(this.find("*"),c.find("*"))}return c},html:function(a){if(a===z)return this[0]&&this[0].nodeType===1?this[0].innerHTML.replace(Sa,""):null;else if(typeof a==="string"&&!Ea.test(a)&&(b.support.leadingWhitespace||!pa.test(a))&&!aa[(Ua.exec(a)||["",""])[1].toLowerCase()]){a=a.replace(Ta,Va);try{for(var c=0,d=this.length;c<d;c++)if(this[c].nodeType===1){b.cleanData(this[c].getElementsByTagName("*"));this[c].innerHTML=a}}catch(f){this.empty().append(a)}}else b.isFunction(a)?this.each(function(e){var i=
b(this),j=i.html();i.empty().append(function(){return a.call(this,e,j)})}):this.empty().append(a);return this},replaceWith:function(a){if(this[0]&&this[0].parentNode){if(b.isFunction(a))return this.each(function(c){var d=b(this),f=d.html();d.replaceWith(a.call(this,c,f))});if(typeof a!=="string")a=b(a).detach();return this.each(function(){var c=this.nextSibling,d=this.parentNode;b(this).remove();c?b(c).before(a):b(d).append(a)})}else return this.pushStack(b(b.isFunction(a)?a():a),"replaceWith",a)},
detach:function(a){return this.remove(a,true)},domManip:function(a,c,d){function f(E){return b.nodeName(E,"table")?E.getElementsByTagName("tbody")[0]||E.appendChild(E.ownerDocument.createElement("tbody")):E}var e,i,j=a[0],r=[],k;if(!b.support.checkClone&&arguments.length===3&&typeof j==="string"&&Fa.test(j))return this.each(function(){b(this).domManip(a,c,d,true)});if(b.isFunction(j))return this.each(function(E){var K=b(this);a[0]=j.call(this,E,c?K.html():z);K.domManip(a,c,d)});if(this[0]){e=j&&j.parentNode;
e=b.support.parentNode&&e&&e.nodeType===11&&e.childNodes.length===this.length?{fragment:e}:R(a,this,r);k=e.fragment;if(i=k.childNodes.length===1?(k=k.firstChild):k.firstChild){c=c&&b.nodeName(i,"tr");for(var q=0,w=this.length;q<w;q++)d.call(c?f(this[q],i):this[q],q>0||e.cacheable||this.length>1?k.cloneNode(true):k)}r.length&&b.each(r,F)}return this}});b.fragments={};b.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},function(a,c){b.fn[a]=
function(d){var f=[];d=b(d);var e=this.length===1&&this[0].parentNode;if(e&&e.nodeType===11&&e.childNodes.length===1&&d.length===1){d[c](this[0]);return this}else{e=0;for(var i=d.length;e<i;e++){var j=(e>0?this.clone(true):this).get();b.fn[c].apply(b(d[e]),j);f=f.concat(j)}return this.pushStack(f,a,d.selector)}}});b.extend({clean:function(a,c,d,f){c=c||m;if(typeof c.createElement==="undefined")c=c.ownerDocument||c[0]&&c[0].ownerDocument||m;for(var e=[],i=0,j;(j=a[i])!=null;i++){if(typeof j==="number")j+=
"";if(j){if(typeof j==="string"&&!kb.test(j))j=c.createTextNode(j);else if(typeof j==="string"){j=j.replace(Ta,Va);var r=(Ua.exec(j)||["",""])[1].toLowerCase(),k=aa[r]||aa._default,q=k[0],w=c.createElement("div");for(w.innerHTML=k[1]+j+k[2];q--;)w=w.lastChild;if(!b.support.tbody){q=jb.test(j);r=r==="table"&&!q?w.firstChild&&w.firstChild.childNodes:k[1]==="<table>"&&!q?w.childNodes:[];for(k=r.length-1;k>=0;--k)b.nodeName(r[k],"tbody")&&!r[k].childNodes.length&&r[k].parentNode.removeChild(r[k])}!b.support.leadingWhitespace&&
pa.test(j)&&w.insertBefore(c.createTextNode(pa.exec(j)[0]),w.firstChild);j=w.childNodes}if(j.nodeType)e.push(j);else e=b.merge(e,j)}}if(d)for(i=0;e[i];i++)if(f&&b.nodeName(e[i],"script")&&(!e[i].type||e[i].type.toLowerCase()==="text/javascript"))f.push(e[i].parentNode?e[i].parentNode.removeChild(e[i]):e[i]);else{e[i].nodeType===1&&e.splice.apply(e,[i+1,0].concat(b.makeArray(e[i].getElementsByTagName("script"))));d.appendChild(e[i])}return e},cleanData:function(a){for(var c,d,f=b.cache,e=b.event.special,
i=b.support.deleteExpando,j=0,r;(r=a[j])!=null;j++)if(d=r[b.expando]){c=f[d];if(c.events)for(var k in c.events)e[k]?b.event.remove(r,k):La(r,k,c.handle);if(i)delete r[b.expando];else r.removeAttribute&&r.removeAttribute(b.expando);delete f[d]}}});var lb=/z-?index|font-?weight|opacity|zoom|line-?height/i,Wa=/alpha\([^)]*\)/,Xa=/opacity=([^)]*)/,za=/float/i,Aa=/-([a-z])/ig,mb=/([A-Z])/g,nb=/^-?\d+(?:px)?$/i,ob=/^-?\d/,pb={position:"absolute",visibility:"hidden",display:"block"},qb=["Left","Right"],
rb=["Top","Bottom"],sb=m.defaultView&&m.defaultView.getComputedStyle,Ya=b.support.cssFloat?"cssFloat":"styleFloat",Ba=function(a,c){return c.toUpperCase()};b.fn.css=function(a,c){return o(this,a,c,true,function(d,f,e){if(e===z)return b.curCSS(d,f);if(typeof e==="number"&&!lb.test(f))e+="px";b.style(d,f,e)})};b.extend({style:function(a,c,d){if(!a||a.nodeType===3||a.nodeType===8)return z;if((c==="width"||c==="height")&&parseFloat(d)<0)d=z;var f=a.style||a,e=d!==z;if(!b.support.opacity&&c==="opacity"){if(e){f.zoom=
1;c=parseInt(d,10)+""==="NaN"?"":"alpha(opacity="+d*100+")";a=f.filter||b.curCSS(a,"filter")||"";f.filter=Wa.test(a)?a.replace(Wa,c):c}return f.filter&&f.filter.indexOf("opacity=")>=0?parseFloat(Xa.exec(f.filter)[1])/100+"":""}if(za.test(c))c=Ya;c=c.replace(Aa,Ba);if(e)f[c]=d;return f[c]},css:function(a,c,d,f){if(c==="width"||c==="height"){var e,i=c==="width"?qb:rb;d=function(){e=c==="width"?a.offsetWidth:a.offsetHeight;f!=="border"&&b.each(i,function(){f||(e-=parseFloat(b.curCSS(a,"padding"+this,
true))||0);if(f==="margin")e+=parseFloat(b.curCSS(a,"margin"+this,true))||0;else e-=parseFloat(b.curCSS(a,"border"+this+"Width",true))||0})};a.offsetWidth!==0?d():b.swap(a,pb,d);return Math.max(0,Math.round(e))}return b.curCSS(a,c,d)},curCSS:function(a,c,d){var f,e=a.style;if(!b.support.opacity&&c==="opacity"&&a.currentStyle){f=Xa.test(a.currentStyle.filter||"")?parseFloat(RegExp.$1)/100+"":"";return f===""?"1":f}if(za.test(c))c=Ya;if(!d&&e&&e[c])f=e[c];else if(sb){if(za.test(c))c="float";c=c.replace(mb,
"-$1").toLowerCase();e=a.ownerDocument.defaultView;if(!e)return null;if(a=e.getComputedStyle(a,null))f=a.getPropertyValue(c);if(c==="opacity"&&f==="")f="1"}else if(a.currentStyle){d=c.replace(Aa,Ba);f=a.currentStyle[c]||a.currentStyle[d];if(!nb.test(f)&&ob.test(f)){c=e.left;var i=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;e.left=d==="fontSize"?"1em":f||0;f=e.pixelLeft+"px";e.left=c;a.runtimeStyle.left=i}}return f},swap:function(a,c,d){var f={};for(var e in c){f[e]=a.style[e];a.style[e]=
c[e]}d.call(a);for(e in c)a.style[e]=f[e]}});if(b.expr&&b.expr.filters){b.expr.filters.hidden=function(a){var c=a.offsetWidth,d=a.offsetHeight,f=a.nodeName.toLowerCase()==="tr";return c===0&&d===0&&!f?true:c>0&&d>0&&!f?false:b.curCSS(a,"display")==="none"};b.expr.filters.visible=function(a){return!b.expr.filters.hidden(a)}}var tb=u(),ub=/<script(.|\s)*?\/script>/gi,vb=/select|textarea/i,wb=/color|date|datetime|email|hidden|month|number|password|range|search|tel|text|time|url|week/i,ia=/=\?(&|$)/,
Ca=/\?/,xb=/(\?|&)_=.*?(&|$)/,yb=/^(\w+:)?\/\/([^\/?#]+)/,zb=/%20/g,Ab=b.fn.load;b.fn.extend({load:function(a,c,d){if(typeof a!=="string")return Ab.call(this,a);else if(!this.length)return this;var f=a.indexOf(" ");if(f>=0){var e=a.slice(f,a.length);a=a.slice(0,f)}f="GET";if(c)if(b.isFunction(c)){d=c;c=null}else if(typeof c==="object"){c=b.param(c,b.ajaxSettings.traditional);f="POST"}var i=this;b.ajax({url:a,type:f,dataType:"html",data:c,complete:function(j,r){if(r==="success"||r==="notmodified")i.html(e?
b("<div />").append(j.responseText.replace(ub,"")).find(e):j.responseText);d&&i.each(d,[j.responseText,r,j])}});return this},serialize:function(){return b.param(this.serializeArray())},serializeArray:function(){return this.map(function(){return this.elements?b.makeArray(this.elements):this}).filter(function(){return this.name&&!this.disabled&&(this.checked||vb.test(this.nodeName)||wb.test(this.type))}).map(function(a,c){a=b(this).val();return a==null?null:b.isArray(a)?b.map(a,function(d){return{name:c.name,
value:d}}):{name:c.name,value:a}}).get()}});b.each("ajaxStart ajaxStop ajaxComplete ajaxError ajaxSuccess ajaxSend".split(" "),function(a,c){b.fn[c]=function(d){return this.bind(c,d)}});b.extend({get:function(a,c,d,f){if(b.isFunction(c)){f=f||d;d=c;c=null}return b.ajax({type:"GET",url:a,data:c,success:d,dataType:f})},getScript:function(a,c){return b.get(a,null,c,"script")},getJSON:function(a,c,d){return b.get(a,c,d,"json")},post:function(a,c,d,f){if(b.isFunction(c)){f=f||d;d=c;c={}}return b.ajax({type:"POST",
url:a,data:c,success:d,dataType:f})},ajaxSetup:function(a){b.extend(b.ajaxSettings,a)},ajaxSettings:{url:location.href,global:true,type:"GET",contentType:"application/x-www-form-urlencoded",processData:true,async:true,xhr:A.XMLHttpRequest&&(A.location.protocol!=="file:"||!A.ActiveXObject)?function(){return new A.XMLHttpRequest}:function(){try{return new A.ActiveXObject("Microsoft.XMLHTTP")}catch(a){}},accepts:{xml:"application/xml, text/xml",html:"text/html",script:"text/javascript, application/javascript",
json:"application/json, text/javascript",text:"text/plain",_default:"*/*"}},lastModified:{},etag:{},ajax:function(a){function c(){e.success&&e.success.call(k,r,j,I);e.global&&f("ajaxSuccess",[I,e])}function d(){e.complete&&e.complete.call(k,I,j);e.global&&f("ajaxComplete",[I,e]);e.global&&!--b.active&&b.event.trigger("ajaxStop")}function f(t,s){(e.context?b(e.context):b.event).trigger(t,s)}var e=b.extend(true,{},b.ajaxSettings,a),i,j,r,k=a&&a.context||e,q=e.type.toUpperCase();if(e.data&&e.processData&&
typeof e.data!=="string")e.data=b.param(e.data,e.traditional);if(e.dataType==="jsonp"){if(q==="GET")ia.test(e.url)||(e.url+=(Ca.test(e.url)?"&":"?")+(e.jsonp||"callback")+"=?");else if(!e.data||!ia.test(e.data))e.data=(e.data?e.data+"&":"")+(e.jsonp||"callback")+"=?";e.dataType="json"}if(e.dataType==="json"&&(e.data&&ia.test(e.data)||ia.test(e.url))){i=e.jsonpCallback||"jsonp"+tb++;if(e.data)e.data=(e.data+"").replace(ia,"="+i+"$1");e.url=e.url.replace(ia,"="+i+"$1");e.dataType="script";A[i]=A[i]||
function(t){r=t;c();d();A[i]=z;try{delete A[i]}catch(s){}K&&K.removeChild(S)}}if(e.dataType==="script"&&e.cache===null)e.cache=false;if(e.cache===false&&q==="GET"){var w=u(),E=e.url.replace(xb,"$1_="+w+"$2");e.url=E+(E===e.url?(Ca.test(e.url)?"&":"?")+"_="+w:"")}if(e.data&&q==="GET")e.url+=(Ca.test(e.url)?"&":"?")+e.data;e.global&&!b.active++&&b.event.trigger("ajaxStart");w=(w=yb.exec(e.url))&&(w[1]&&w[1]!==location.protocol||w[2]!==location.host);if(e.dataType==="script"&&q==="GET"&&w){var K=m.getElementsByTagName("head")[0]||
m.documentElement,S=m.createElement("script");S.src=e.url;if(e.scriptCharset)S.charset=e.scriptCharset;if(!i){var Q=false;S.onload=S.onreadystatechange=function(){if(!Q&&(!this.readyState||this.readyState==="loaded"||this.readyState==="complete")){Q=true;c();d();S.onload=S.onreadystatechange=null;K&&S.parentNode&&K.removeChild(S)}}}K.insertBefore(S,K.firstChild);return z}var $=false,I=e.xhr();if(I){e.username?I.open(q,e.url,e.async,e.username,e.password):I.open(q,e.url,e.async);try{if(e.data||a&&
a.contentType)I.setRequestHeader("Content-Type",e.contentType);if(e.ifModified){b.lastModified[e.url]&&I.setRequestHeader("If-Modified-Since",b.lastModified[e.url]);b.etag[e.url]&&I.setRequestHeader("If-None-Match",b.etag[e.url])}w||I.setRequestHeader("X-Requested-With","XMLHttpRequest");I.setRequestHeader("Accept",e.dataType&&e.accepts[e.dataType]?e.accepts[e.dataType]+", */*":e.accepts._default)}catch(ya){}if(e.beforeSend&&e.beforeSend.call(k,I,e)===false){e.global&&!--b.active&&b.event.trigger("ajaxStop");
I.abort();return false}e.global&&f("ajaxSend",[I,e]);var g=I.onreadystatechange=function(t){if(!I||I.readyState===0||t==="abort"){$||d();$=true;if(I)I.onreadystatechange=b.noop}else if(!$&&I&&(I.readyState===4||t==="timeout")){$=true;I.onreadystatechange=b.noop;j=t==="timeout"?"timeout":!b.httpSuccess(I)?"error":e.ifModified&&b.httpNotModified(I,e.url)?"notmodified":"success";var s;if(j==="success")try{r=b.httpData(I,e.dataType,e)}catch(G){j="parsererror";s=G}if(j==="success"||j==="notmodified")i||
c();else b.handleError(e,I,j,s);d();t==="timeout"&&I.abort();if(e.async)I=null}};try{var h=I.abort;I.abort=function(){I&&h.call(I);g("abort")}}catch(l){}e.async&&e.timeout>0&&setTimeout(function(){I&&!$&&g("timeout")},e.timeout);try{I.send(q==="POST"||q==="PUT"||q==="DELETE"?e.data:null)}catch(p){b.handleError(e,I,null,p);d()}e.async||g();return I}},handleError:function(a,c,d,f){if(a.error)a.error.call(a.context||a,c,d,f);if(a.global)(a.context?b(a.context):b.event).trigger("ajaxError",[c,a,f])},
active:0,httpSuccess:function(a){try{return!a.status&&location.protocol==="file:"||a.status>=200&&a.status<300||a.status===304||a.status===1223||a.status===0}catch(c){}return false},httpNotModified:function(a,c){var d=a.getResponseHeader("Last-Modified"),f=a.getResponseHeader("Etag");if(d)b.lastModified[c]=d;if(f)b.etag[c]=f;return a.status===304||a.status===0},httpData:function(a,c,d){var f=a.getResponseHeader("content-type")||"",e=c==="xml"||!c&&f.indexOf("xml")>=0;a=e?a.responseXML:a.responseText;
e&&a.documentElement.nodeName==="parsererror"&&b.error("parsererror");if(d&&d.dataFilter)a=d.dataFilter(a,c);if(typeof a==="string")if(c==="json"||!c&&f.indexOf("json")>=0)a=b.parseJSON(a);else if(c==="script"||!c&&f.indexOf("javascript")>=0)b.globalEval(a);return a},param:function(a,c){function d(j,r){if(b.isArray(r))b.each(r,function(k,q){c||/\[\]$/.test(j)?f(j,q):d(j+"["+(typeof q==="object"||b.isArray(q)?k:"")+"]",q)});else!c&&r!=null&&typeof r==="object"?b.each(r,function(k,q){d(j+"["+k+"]",
q)}):f(j,r)}function f(j,r){r=b.isFunction(r)?r():r;e[e.length]=encodeURIComponent(j)+"="+encodeURIComponent(r)}var e=[];if(c===z)c=b.ajaxSettings.traditional;if(b.isArray(a)||a.jquery)b.each(a,function(){f(this.name,this.value)});else for(var i in a)d(i,a[i]);return e.join("&").replace(zb,"+")}});var Da={},Bb=/toggle|show|hide/,Cb=/^([+-]=)?([\d+-.]+)(.*)$/,qa,Ga=[["height","marginTop","marginBottom","paddingTop","paddingBottom"],["width","marginLeft","marginRight","paddingLeft","paddingRight"],
["opacity"]];b.fn.extend({show:function(a,c){if(a||a===0)return this.animate(L("show",3),a,c);else{a=0;for(c=this.length;a<c;a++){var d=b.data(this[a],"olddisplay");this[a].style.display=d||"";if(b.css(this[a],"display")==="none"){d=this[a].nodeName;var f;if(Da[d])f=Da[d];else{var e=b("<"+d+" />").appendTo("body");f=e.css("display");if(f==="none")f="block";e.remove();Da[d]=f}b.data(this[a],"olddisplay",f)}}a=0;for(c=this.length;a<c;a++)this[a].style.display=b.data(this[a],"olddisplay")||"";return this}},
hide:function(a,c){if(a||a===0)return this.animate(L("hide",3),a,c);else{a=0;for(c=this.length;a<c;a++){var d=b.data(this[a],"olddisplay");!d&&d!=="none"&&b.data(this[a],"olddisplay",b.css(this[a],"display"))}a=0;for(c=this.length;a<c;a++)this[a].style.display="none";return this}},_toggle:b.fn.toggle,toggle:function(a,c){var d=typeof a==="boolean";if(b.isFunction(a)&&b.isFunction(c))this._toggle.apply(this,arguments);else a==null||d?this.each(function(){var f=d?a:b(this).is(":hidden");b(this)[f?"show":
"hide"]()}):this.animate(L("toggle",3),a,c);return this},fadeTo:function(a,c,d){return this.filter(":hidden").css("opacity",0).show().end().animate({opacity:c},a,d)},animate:function(a,c,d,f){var e=b.speed(c,d,f);if(b.isEmptyObject(a))return this.each(e.complete);return this[e.queue===false?"each":"queue"](function(){var i=b.extend({},e),j,r=this.nodeType===1&&b(this).is(":hidden"),k=this;for(j in a){var q=j.replace(Aa,Ba);if(j!==q){a[q]=a[j];delete a[j];j=q}if(a[j]==="hide"&&r||a[j]==="show"&&!r)return i.complete.call(this);
if((j==="height"||j==="width")&&this.style){i.display=b.css(this,"display");i.overflow=this.style.overflow}if(b.isArray(a[j])){(i.specialEasing=i.specialEasing||{})[j]=a[j][1];a[j]=a[j][0]}}if(i.overflow!=null)this.style.overflow="hidden";i.curAnim=b.extend({},a);b.each(a,function(w,E){var K=new b.fx(k,i,w);if(Bb.test(E))K[E==="toggle"?r?"show":"hide":E](a);else{var S=Cb.exec(E),Q=K.cur(true)||0;if(S){E=parseFloat(S[2]);var $=S[3]||"px";if($!=="px"){k.style[w]=(E||1)+$;Q=(E||1)/K.cur(true)*Q;k.style[w]=
Q+$}if(S[1])E=(S[1]==="-="?-1:1)*E+Q;K.custom(Q,E,$)}else K.custom(Q,E,"")}});return true})},stop:function(a,c){var d=b.timers;a&&this.queue([]);this.each(function(){for(var f=d.length-1;f>=0;f--)if(d[f].elem===this){c&&d[f](true);d.splice(f,1)}});c||this.dequeue();return this}});b.each({slideDown:L("show",1),slideUp:L("hide",1),slideToggle:L("toggle",1),fadeIn:{opacity:"show"},fadeOut:{opacity:"hide"}},function(a,c){b.fn[a]=function(d,f){return this.animate(c,d,f)}});b.extend({speed:function(a,c,
d){var f=a&&typeof a==="object"?a:{complete:d||!d&&c||b.isFunction(a)&&a,duration:a,easing:d&&c||c&&!b.isFunction(c)&&c};f.duration=b.fx.off?0:typeof f.duration==="number"?f.duration:b.fx.speeds[f.duration]||b.fx.speeds._default;f.old=f.complete;f.complete=function(){f.queue!==false&&b(this).dequeue();b.isFunction(f.old)&&f.old.call(this)};return f},easing:{linear:function(a,c,d,f){return d+f*a},swing:function(a,c,d,f){return(-Math.cos(a*Math.PI)/2+0.5)*f+d}},timers:[],fx:function(a,c,d){this.options=
c;this.elem=a;this.prop=d;if(!c.orig)c.orig={}}});b.fx.prototype={update:function(){this.options.step&&this.options.step.call(this.elem,this.now,this);(b.fx.step[this.prop]||b.fx.step._default)(this);if((this.prop==="height"||this.prop==="width")&&this.elem.style)this.elem.style.display="block"},cur:function(a){if(this.elem[this.prop]!=null&&(!this.elem.style||this.elem.style[this.prop]==null))return this.elem[this.prop];return(a=parseFloat(b.css(this.elem,this.prop,a)))&&a>-10000?a:parseFloat(b.curCSS(this.elem,
this.prop))||0},custom:function(a,c,d){function f(i){return e.step(i)}this.startTime=u();this.start=a;this.end=c;this.unit=d||this.unit||"px";this.now=this.start;this.pos=this.state=0;var e=this;f.elem=this.elem;if(f()&&b.timers.push(f)&&!qa)qa=setInterval(b.fx.tick,13)},show:function(){this.options.orig[this.prop]=b.style(this.elem,this.prop);this.options.show=true;this.custom(this.prop==="width"||this.prop==="height"?1:0,this.cur());b(this.elem).show()},hide:function(){this.options.orig[this.prop]=
b.style(this.elem,this.prop);this.options.hide=true;this.custom(this.cur(),0)},step:function(a){var c=u(),d=true;if(a||c>=this.options.duration+this.startTime){this.now=this.end;this.pos=this.state=1;this.update();this.options.curAnim[this.prop]=true;for(var f in this.options.curAnim)if(this.options.curAnim[f]!==true)d=false;if(d){if(this.options.display!=null){this.elem.style.overflow=this.options.overflow;a=b.data(this.elem,"olddisplay");this.elem.style.display=a?a:this.options.display;if(b.css(this.elem,
"display")==="none")this.elem.style.display="block"}this.options.hide&&b(this.elem).hide();if(this.options.hide||this.options.show)for(var e in this.options.curAnim)b.style(this.elem,e,this.options.orig[e]);this.options.complete.call(this.elem)}return false}else{e=c-this.startTime;this.state=e/this.options.duration;a=this.options.easing||(b.easing.swing?"swing":"linear");this.pos=b.easing[this.options.specialEasing&&this.options.specialEasing[this.prop]||a](this.state,e,0,1,this.options.duration);
this.now=this.start+(this.end-this.start)*this.pos;this.update()}return true}};b.extend(b.fx,{tick:function(){for(var a=b.timers,c=0;c<a.length;c++)a[c]()||a.splice(c--,1);a.length||b.fx.stop()},stop:function(){clearInterval(qa);qa=null},speeds:{slow:600,fast:200,_default:400},step:{opacity:function(a){b.style(a.elem,"opacity",a.now)},_default:function(a){if(a.elem.style&&a.elem.style[a.prop]!=null)a.elem.style[a.prop]=(a.prop==="width"||a.prop==="height"?Math.max(0,a.now):a.now)+a.unit;else a.elem[a.prop]=
a.now}}});if(b.expr&&b.expr.filters)b.expr.filters.animated=function(a){return b.grep(b.timers,function(c){return a===c.elem}).length};b.fn.offset="getBoundingClientRect"in m.documentElement?function(a){var c=this[0];if(a)return this.each(function(e){b.offset.setOffset(this,a,e)});if(!c||!c.ownerDocument)return null;if(c===c.ownerDocument.body)return b.offset.bodyOffset(c);var d=c.getBoundingClientRect(),f=c.ownerDocument;c=f.body;f=f.documentElement;return{top:d.top+(self.pageYOffset||b.support.boxModel&&
f.scrollTop||c.scrollTop)-(f.clientTop||c.clientTop||0),left:d.left+(self.pageXOffset||b.support.boxModel&&f.scrollLeft||c.scrollLeft)-(f.clientLeft||c.clientLeft||0)}}:function(a){var c=this[0];if(a)return this.each(function(w){b.offset.setOffset(this,a,w)});if(!c||!c.ownerDocument)return null;if(c===c.ownerDocument.body)return b.offset.bodyOffset(c);b.offset.initialize();var d=c.offsetParent,f=c,e=c.ownerDocument,i,j=e.documentElement,r=e.body;f=(e=e.defaultView)?e.getComputedStyle(c,null):c.currentStyle;
for(var k=c.offsetTop,q=c.offsetLeft;(c=c.parentNode)&&c!==r&&c!==j;){if(b.offset.supportsFixedPosition&&f.position==="fixed")break;i=e?e.getComputedStyle(c,null):c.currentStyle;k-=c.scrollTop;q-=c.scrollLeft;if(c===d){k+=c.offsetTop;q+=c.offsetLeft;if(b.offset.doesNotAddBorder&&!(b.offset.doesAddBorderForTableAndCells&&/^t(able|d|h)$/i.test(c.nodeName))){k+=parseFloat(i.borderTopWidth)||0;q+=parseFloat(i.borderLeftWidth)||0}f=d;d=c.offsetParent}if(b.offset.subtractsBorderForOverflowNotVisible&&i.overflow!==
"visible"){k+=parseFloat(i.borderTopWidth)||0;q+=parseFloat(i.borderLeftWidth)||0}f=i}if(f.position==="relative"||f.position==="static"){k+=r.offsetTop;q+=r.offsetLeft}if(b.offset.supportsFixedPosition&&f.position==="fixed"){k+=Math.max(j.scrollTop,r.scrollTop);q+=Math.max(j.scrollLeft,r.scrollLeft)}return{top:k,left:q}};b.offset={initialize:function(){var a=m.body,c=m.createElement("div"),d,f,e,i=parseFloat(b.curCSS(a,"marginTop",true))||0;b.extend(c.style,{position:"absolute",top:0,left:0,margin:0,
border:0,width:"1px",height:"1px",visibility:"hidden"});c.innerHTML="<div style='position:absolute;top:0;left:0;margin:0;border:5px solid #000;padding:0;width:1px;height:1px;'><div></div></div><table style='position:absolute;top:0;left:0;margin:0;border:5px solid #000;padding:0;width:1px;height:1px;' cellpadding='0' cellspacing='0'><tr><td></td></tr></table>";a.insertBefore(c,a.firstChild);d=c.firstChild;f=d.firstChild;e=d.nextSibling.firstChild.firstChild;this.doesNotAddBorder=f.offsetTop!==5;this.doesAddBorderForTableAndCells=
e.offsetTop===5;f.style.position="fixed";f.style.top="20px";this.supportsFixedPosition=f.offsetTop===20||f.offsetTop===15;f.style.position=f.style.top="";d.style.overflow="hidden";d.style.position="relative";this.subtractsBorderForOverflowNotVisible=f.offsetTop===-5;this.doesNotIncludeMarginInBodyOffset=a.offsetTop!==i;a.removeChild(c);b.offset.initialize=b.noop},bodyOffset:function(a){var c=a.offsetTop,d=a.offsetLeft;b.offset.initialize();if(b.offset.doesNotIncludeMarginInBodyOffset){c+=parseFloat(b.curCSS(a,
"marginTop",true))||0;d+=parseFloat(b.curCSS(a,"marginLeft",true))||0}return{top:c,left:d}},setOffset:function(a,c,d){if(/static/.test(b.curCSS(a,"position")))a.style.position="relative";var f=b(a),e=f.offset(),i=parseInt(b.curCSS(a,"top",true),10)||0,j=parseInt(b.curCSS(a,"left",true),10)||0;if(b.isFunction(c))c=c.call(a,d,e);d={top:c.top-e.top+i,left:c.left-e.left+j};"using"in c?c.using.call(a,d):f.css(d)}};b.fn.extend({position:function(){if(!this[0])return null;var a=this[0],c=this.offsetParent(),
d=this.offset(),f=/^body|html$/i.test(c[0].nodeName)?{top:0,left:0}:c.offset();d.top-=parseFloat(b.curCSS(a,"marginTop",true))||0;d.left-=parseFloat(b.curCSS(a,"marginLeft",true))||0;f.top+=parseFloat(b.curCSS(c[0],"borderTopWidth",true))||0;f.left+=parseFloat(b.curCSS(c[0],"borderLeftWidth",true))||0;return{top:d.top-f.top,left:d.left-f.left}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent||m.body;a&&!/^body|html$/i.test(a.nodeName)&&b.css(a,"position")==="static";)a=
a.offsetParent;return a})}});b.each(["Left","Top"],function(a,c){var d="scroll"+c;b.fn[d]=function(f){var e=this[0],i;if(!e)return null;if(f!==z)return this.each(function(){if(i=n(this))i.scrollTo(!a?f:b(i).scrollLeft(),a?f:b(i).scrollTop());else this[d]=f});else return(i=n(e))?"pageXOffset"in i?i[a?"pageYOffset":"pageXOffset"]:b.support.boxModel&&i.document.documentElement[d]||i.document.body[d]:e[d]}});b.each(["Height","Width"],function(a,c){var d=c.toLowerCase();b.fn["inner"+c]=function(){return this[0]?
b.css(this[0],d,false,"padding"):null};b.fn["outer"+c]=function(f){return this[0]?b.css(this[0],d,false,f?"margin":"border"):null};b.fn[d]=function(f){var e=this[0];if(!e)return f==null?null:this;if(b.isFunction(f))return this.each(function(i){var j=b(this);j[d](f.call(this,i,j[d]()))});return"scrollTo"in e&&e.document?e.document.compatMode==="CSS1Compat"&&e.document.documentElement["client"+c]||e.document.body["client"+c]:e.nodeType===9?Math.max(e.documentElement["client"+c],e.body["scroll"+c],e.documentElement["scroll"+
c],e.body["offset"+c],e.documentElement["offset"+c]):f===z?b.css(e,d):this.css(d,typeof f==="string"?f:f+"px")}});A.jQuery=A.$=b;if(ka){require.callReady=b.callReady;require.def("jquery",function(){return b});require.def("jQuery",function(){return b})}})(window);
